#p ona li, 815
#p ni li, 652
#p li lon, 507
#p li kama, 492
#p jan li, 433
#p li pona, 374
#p la mi, 325
#p li ken, 303
#p jo e, 298
#p pana e, 291
#p e ni, 291
#p ala e, 284
#p li tawa, 279
#p mi wile, 267
#p mi li, 257
#p ni la, 247
#p lukin e, 244
#p tawa mi, 240
#p sona e, 211
#p li wile, 210
#p toki e, 209
#p mute li, 205
#p pali e, 204
#p li toki, 198
#p la jan, 197
#p ken ala, 186
#p la ona, 181
#p e ona, 181
#p pona tawa, 177
#p lon tenpo, 171
#p li jo, 168
#p sina wile, 161
#p la sina, 161
#p toki pona, 158
#p sina li, 157
#p pi jan, 155
#p wile e, 154
#p tu li, 151
#p li pana, 148
#p e mi, 147
#p soweli li, 141
#p ale li, 141
#p mi ken, 139
#p wile ala, 136
#p e jan, 131
#p tawa sina, 129
#p e sina, 128
#p lon poka, 123
#p tawa jan, 122
#p li pali, 122
#p li ike, 121
#p jan tu, 120
#p sina ken, 119
#p moku e, 119
#p e ijo, 119
#p li pilin, 116
#p la o, 115
#p pi toki, 108
#p li awen, 108
#p weka e, 107
#p e toki, 107
#p mi sona, 101
#p o tawa, 98
#p seme li, 97
#p lon ma, 97
#p mi pilin, 96
#p li lukin, 96
#p anu seme, 96
#p li weka, 95
#p mi la, 94
#p e nasin, 92
#p sona ala, 91
#p ala li, 91
#p mi o, 90
#p jan pi, 90
#p e soweli, 90
#p e lipu, 90
#p li suli, 89
#p lili li, 87
#p pona li, 86
#p ilo o, 86
#p o pana, 84
#p ken la, 84
#p pilin ike, 83
#p tenpo suno, 82
#p e nimi, 82
#p pilin e, 81
#p e kili, 81
#p pona mute, 79
#p li pakala, 78
#p jan ale, 78
#p ike tawa, 78
#p e telo, 78
#p li sama, 77
#p kute e, 77
#p kama jo, 77
#p jan mute, 77
#p lon tomo, 76
#p tenpo ni, 74
#p olin e, 74
#p mi tawa, 74
#p kama lon, 74
#p pona e, 73
#p li tan, 72
#p mi lukin, 71
#p li sona, 71
#p tan seme, 70
#p o lukin, 70
#p pi ma, 69
#p pilin pona, 69
#p o kama, 69
#p mi kama, 69
#p tomo tawa, 67
#p kama sona, 67
#p e tomo, 67
#p o toki, 66
#p pakala e, 65
#p la ni, 65
#p e len, 65
#p ale la, 65
#p tenpo pini, 64
#p tawa tomo, 64
#p suli li, 64
#p mi tu, 64
#p ma tomo, 63
#p e ilo, 63
#p awen lon, 63
#p tawa ma, 62
#p tawa lon, 62
#p li moku, 62
#p sina la, 60
#p ma li, 60
#p li kepeken, 60
#p pona ala, 59
#p nanpa wan, 59
#p li jan, 59
#p jan o, 59
#p e seme, 59
#p seme la, 58
#p e sona, 57
#p e sitelen, 57
#p tenpo ale, 56
#p alasa e, 56
#p jan ante, 55
#p ante li, 55
#p li seme, 54
#p lipu ni, 54
#p li nasa, 54
#p li alasa, 54
#p kalama musi, 54
#p jan pona, 54
#p jan lawa, 54
#p lon ala, 53
#p kala li, 53
#p jan lili, 53
#p tomo mi, 52
#p suno li, 52
#p o weka, 52
#p o awen, 52
#p li pini, 52
#p kama tawa, 52
#p e pilin, 52
#p e moku, 52
#p weka tan, 51
#p tawa ona, 51
#p taso mi, 51
#p tan ma, 51
#p pilin mi, 51
#p ni tawa, 51
#p mi toki, 51
#p li lili, 51
#p pini la, 50
#p mi lon, 50
#p mi jo, 50
#p wile sona, 49
#p wan li, 49
#p pini e, 49
#p kin li, 49
#p e pona, 49
#p kama tan, 48
#p kama la, 48
#p ilo nanpa, 48
#p sina sona, 47
#p lon sewi, 46
#p li open, 46
#p e ale, 46
#p ala tawa, 46
#p ala ken, 46
#p sina kepeken, 45
#p sewi li, 45
#p pona lukin, 45
#p o kepeken, 45
#p mute e, 45
#p li musi, 45
#p toki tawa, 44
#p tenpo pimeja, 44
#p sina toki, 44
#p olin li, 44
#p jan olin, 44
#p ala lon, 44
#p wile tawa, 43
#p tenpo kama, 43
#p taso ona, 43
#p sina lon, 43
#p nasin ni, 43
#p kepeken ilo, 43
#p e luka, 43
#p ante e, 43
#p tawa e, 42
#p tan ni, 42
#p nimi li, 42
#p li kalama, 42
#p kin la, 42
#p wile kama, 41
#p wan taso, 41
#p e tenpo, 41
#p e mani, 41
#p pi mute, 40
#p lawa li, 40
#p kepeken nimi, 40
#p waso li, 39
#p poka pi, 39
#p mi olin, 39
#p lili la, 39
#p ike li, 39
#p en jan, 39
#p e kasi, 39
#p wile moku, 38
#p telo li, 38
#p tawa li, 38
#p nimi pi, 38
#p mi pana, 38
#p lon ni, 38
#p lon insa, 38
#p jo ala, 38
#p e ma, 38
#p tu wan, 37
#p tu tu, 37
#p taso li, 37
#p pi tomo, 37
#p mute a, 37
#p mi pali, 37
#p li wawa, 37
#p e kon, 37
#p tawa ni, 36
#p sina pilin, 36
#p poka mi, 36
#p mi mute, 36
#p jan seme, 36
#p ala wile, 36
#p tomo ni, 35
#p toki ala, 35
#p suli la, 35
#p sitelen tawa, 35
#p sina tawa, 35
#p ona la, 35
#p nasin pi, 35
#p nanpa li, 35
#p mi jan, 35
#p ma ni, 35
#p kama pona, 35
#p e poki, 35
#p ali li, 35
#p toki mi, 34
#p tan jan, 34
#p sitelen e, 34
#p pona la, 34
#p pi telo, 34
#p pi soweli, 34
#p nasin seme, 34
#p lukin ala, 34
#p lon nasin, 34
#p ken kama, 34
#p ike mute, 34
#p e kalama, 34
#p tenpo mute, 33
#p tawa anpa, 33
#p sina lukin, 33
#p pi tenpo, 33
#p ona lon, 33
#p o moku, 33
#p o mi, 33
#p lukin tawa, 33
#p lon supa, 33
#p tenpo suli, 32
#p taso la, 32
#p taso jan, 32
#p mute tawa, 32
#p mute la, 32
#p ma kasi, 32
#p li suwi, 32
#p lili mute, 32
#p kepeken tenpo, 32
#p ken toki, 32
#p ken lukin, 32
#p kama ala, 32
#p ilo li, 32
#p e wile, 32
#p e pan, 32
#p e kala, 32
#p awen e, 32
#p ala pona, 32
#p ala la, 32
#p tenpo li, 31
#p pi pona, 31
#p musi ni, 31
#p musi li, 31
#p luka e, 31
#p lon poki, 31
#p lon monsi, 31
#p la nimi, 31
#p jan ala, 31
#p ilo ni, 31
#p soweli lili, 30
#p sona pi, 30
#p o sina, 30
#p o pilin, 30
#p open e, 30
#p ona tu, 30
#p luka tu, 30
#p lon anpa, 30
#p jan kala, 30
#p e ko, 30
#p toki sina, 29
#p tan mi, 29
#p o o, 29
#p mi kepeken, 29
#p lon seme, 29
#p kepeken nasin, 29
#p kasi li, 29
#p e suno, 29
#p ale ni, 29
#p ala lukin, 29
#p tenpo lili, 28
#p sina kama, 28
#p o pali, 28
#p ni lon, 28
#p lon lipu, 28
#p la soweli, 28
#p ken pali, 28
#p e olin, 28
#p telo suli, 27
#p tawa wawa, 27
#p sin li, 27
#p sina jan, 27
#p pi ilo, 27
#p nasa li, 27
#p musi pi, 27
#p mun li, 27
#p li mu, 27
#p kepeken ala, 27
#p jan ni, 27
#p jan ike, 27
#p e nanpa, 27
#p e ike, 27
#p wawa li, 26
#p toki li, 26
#p tawa weka, 26
#p pona lon, 26
#p poka sina, 26
#p nasin nanpa, 26
#p li jaki, 26
#p li ante, 26
#p lawa pi, 26
#p lawa e, 26
#p kasi ni, 26
#p ilo toki, 26
#p ike la, 26
#p e sijelo, 26
#p e lupa, 26
#p pona a, 25
#p pi kasi, 25
#p mi awen, 25
#p li luka, 25
#p li laso, 25
#p li e, 25
#p jan sewi, 25
#p ike ala, 25
#p tomo li, 24
#p tawa sewi, 24
#p tawa ala, 24
#p suno ni, 24
#p sina pali, 24
#p sina o, 24
#p pona mi, 24
#p ona tawa, 24
#p olin mi, 24
#p moku li, 24
#p mije li, 24
#p lon ona, 24
#p lon la, 24
#p loje li, 24
#p li soweli, 24
#p li moli, 24
#p kule li, 24
#p ken tawa, 24
#p e mute, 24
#p ante la, 24
#p ale pi, 24
#p tomo pi, 23
#p tomo ona, 23
#p toki ni, 23
#p tawa musi, 23
#p tawa kulupu, 23
#p tawa insa, 23
#p tan ona, 23
#p soweli ni, 23
#p sin e, 23
#p sina pona, 23
#p sina jo, 23
#p pi lipu, 23
#p pi kulupu, 23
#p o pakala, 23
#p nanpa tu, 23
#p mute lon, 23
#p mi moku, 23
#p mama mi, 23
#p li olin, 23
#p li mute, 23
#p li kute, 23
#p len pi, 23
#p kepeken toki, 23
#p ken pana, 23
#p kama sin, 23
#p e sike, 23
#p e linja, 23
#p ala sona, 23
#p tu o, 22
#p tenpo pi, 22
#p telo nasa, 22
#p sona li, 22
#p pi nasin, 22
#p ni kepeken, 22
#p moku ala, 22
#p lukin la, 22
#p luka pi, 22
#p lipu pi, 22
#p li len, 22
#p li kule, 22
#p len e, 22
#p kulupu pi, 22
#p kon li, 22
#p kasi suli, 22
#p jan sona, 22
#p akesi li, 22
#p wawa e, 21
#p utala e, 21
#p tawa soweli, 21
#p tan sewi, 21
#p pona taso, 21
#p pi pilin, 21
#p pi lili, 21
#p o pini, 21
#p o kute, 21
#p mute pi, 21
#p lon sinpin, 21
#p lon li, 21
#p li suno, 21
#p lipu li, 21
#p lili taso, 21
#p ken lon, 21
#p ike tan, 21
#p e pipi, 21
#p e musi, 21
#p tawa waso, 20
#p tawa telo, 20
#p suli pi, 20
#p suli mute, 20
#p sitelen pi, 20
#p seli li, 20
#p pimeja li, 20
#p pali ala, 20
#p pakala ala, 20
#p o e, 20
#p musi e, 20
#p moli e, 20
#p mi kin, 20
#p lupa tomo, 20
#p li nasin, 20
#p lili pi, 20
#p li jelo, 20
#p kulupu ni, 20
#p kepeken len, 20
#p ken sona, 20
#p ilo sona, 20
#p e pali, 20
#p e lon, 20
#p anpa e, 20
#p wile lukin, 19
#p wawa la, 19
#p toki pi, 19
#p suli ala, 19
#p soweli pi, 19
#p soweli mi, 19
#p sina moku, 19
#p sewi pi, 19
#p pona anu, 19
#p pi nimi, 19
#p pi nanpa, 19
#p o sona, 19
#p olin sina, 19
#p nimi ni, 19
#p mi ale, 19
#p ma pi, 19
#p lukin li, 19
#p luka sina, 19
#p luka ona, 19
#p li lape, 19
#p len mi, 19
#p la tenpo, 19
#p ko nasa, 19
#p kama weka, 19
#p kama anpa, 19
#p ijo mute, 19
#p ijo li, 19
#p e lawa, 19
#p ala kute, 19
#p ala a, 19
#p wile pana, 18
#p wan la, 18
#p tu en, 18
#p tenpo seme, 18
#p telo e, 18
#p suli tawa, 18
#p sitelen ni, 18
#p sina taso, 18
#p pi wile, 18
#p o jo, 18
#p meli li, 18
#p mani mute, 18
#p ma ante, 18
#p ma ale, 18
#p li lawa, 18
#p len noka, 18
#p len ni, 18
#p kute ala, 18
#p kili ni, 18
#p kepeken ona, 18
#p insa pi, 18
#p ike e, 18
#p ike a, 18
#p e waso, 18
#p e palisa, 18
#p a mi, 18
#p wile pali, 17
#p suli lon, 17
#p sona ni, 17
#p sinpin pi, 17
#p sina kute, 17
#p pona pi, 17
#p pona nanpa, 17
#p pipi li, 17
#p pi pali, 17
#p oko mi, 17
#p nanpa pi, 17
#p mute seme, 17
#p mute mute, 17
#p mi pona, 17
#p mi en, 17
#p luka wan, 17
#p luka luka, 17
#p li utala, 17
#p li tenpo, 17
#p lipu kasi, 17
#p li anpa, 17
#p li ala, 17
#p la nasin, 17
#p kepeken luka, 17
#p ken kepeken, 17
#p kama pakala, 17
#p jelo li, 17
#p jan pali, 17
#p jan ali, 17
#p insa tomo, 17
#p e suwi, 17
#p e oko, 17
#p e ken, 17
#p ala toki, 17
#p ala kama, 17
#p wile toki, 16
#p weka ala, 16
#p tawa kepeken, 16
#p taso e, 16
#p supa lape, 16
#p sina tan, 16
#p sina pana, 16
#p sike lukin, 16
#p pona tan, 16
#p pan li, 16
#p pakala li, 16
#p o ni, 16
#p ona o, 16
#p o lape, 16
#p nasa tawa, 16
#p mi tan, 16
#p mi kute, 16
#p mi e, 16
#p lon telo, 16
#p li sike, 16
#p lete li, 16
#p lawa ona, 16
#p laso li, 16
#p ken ante, 16
#p ilo pi, 16
#p e tan, 16
#p e sinpin, 16
#p e kule, 16
#p wile lon, 15
#p wawa ala, 15
#p walo li, 15
#p tomo la, 15
#p toki kepeken, 15
#p tawa poka, 15
#p tan toki, 15
#p tan sina, 15
#p sina olin, 15
#p sike e, 15
#p pi sike, 15
#p pana ala, 15
#p o open, 15
#p ni tan, 15
#p mi lape, 15
#p mi alasa, 15
#p mama ona, 15
#p lukin mi, 15
#p lon luka, 15
#p lon ilo, 15
#p li seli, 15
#p lili tawa, 15
#p len li, 15
#p lawa mi, 15
#p lape mi, 15
#p kili li, 15
#p ken e, 15
#p kasi kule, 15
#p e kiwen, 15
#p awen tawa, 15
#p wile lape, 14
#p tomo sina, 14
#p tenpo ala, 14
#p tawa nasin, 14
#p suno kama, 14
#p sona pona, 14
#p sijelo sina, 14
#p sijelo mi, 14
#p sijelo li, 14
#p seme lon, 14
#p seli e, 14
#p sama sina, 14
#p pu ala, 14
#p poki ni, 14
#p pi suli, 14
#p pi sona, 14
#p pilin sina, 14
#p pali li, 14
#p o wile, 14
#p ona tan, 14
#p olin ona, 14
#p olin ala, 14
#p nimi sin, 14
#p nasin li, 14
#p nanpa lili, 14
#p mi weka, 14
#p mi taso, 14
#p mi sitelen, 14
#p mi pakala, 14
#p luka mi, 14
#p lon lupa, 14
#p lon kulupu, 14
#p li walo, 14
#p li ijo, 14
#p lape lon, 14
#p lape ala, 14
#p la ijo, 14
#p kule pi, 14
#p kama suli, 14
#p kama lili, 14
#p kama ike, 14
#p jan suli, 14
#p insa e, 14
#p e kulupu, 14
#p tu ni, 13
#p toki sin, 13
#p toki lon, 13
#p toki insa, 13
#p tawa pi, 13
#p suli ni, 13
#p soweli suli, 13
#p sona mi, 13
#p sitelen pona, 13
#p sina ala, 13
#p selo pi, 13
#p sama ni, 13
#p sama ala, 13
#p poka ona, 13
#p pini pi, 13
#p pi kama, 13
#p pali pi, 13
#p o pona, 13
#p o lon, 13
#p nimi mute, 13
#p ni anu, 13
#p nasin sitelen, 13
#p musi lon, 13
#p moli ala, 13
#p mi pi, 13
#p luka li, 13
#p lon toki, 13
#p lon pini, 13
#p lon a, 13
#p li lete, 13
#p len ona, 13
#p kulupu mama, 13
#p kulupu li, 13
#p kon tawa, 13
#p kiwen li, 13
#p kili pi, 13
#p ken pona, 13
#p ilo tenpo, 13
#p ijo pi, 13
#p e selo, 13
#p awen li, 13
#p ante kin, 13
#p wile sina, 12
#p wawa mute, 12
#p wan tawa, 12
#p wan e, 12
#p utala li, 12
#p tomo suli, 12
#p tomo moku, 12
#p tenpo sike, 12
#p tawa sike, 12
#p tawa poki, 12
#p suli e, 12
#p sona mute, 12
#p sina en, 12
#p sina awen, 12
#p pi sitelen, 12
#p pi pu, 12
#p pi olin, 12
#p pi mi, 12
#p pilin sama, 12
#p pali mi, 12
#p oko e, 12
#p nimi pu, 12
#p nimi ona, 12
#p mute ala, 12
#p musi utala, 12
#p monsi ona, 12
#p moli li, 12
#p moku pona, 12
#p moku mute, 12
#p mama li, 12
#p ma lon, 12
#p ma la, 12
#p lupa pi, 12
#p lupa li, 12
#p lon pilin, 12
#p lon jan, 12
#p linja lawa, 12
#p li ma, 12
#p len sina, 12
#p la telo, 12
#p la ma, 12
#p la ale, 12
#p kepeken wawa, 12
#p ken weka, 12
#p ken kute, 12
#p jan tawa, 12
#p e tawa, 12
#p e pakala, 12
#p en mi, 12
#p e meli, 12
#p e lukin, 12
#p anpa li, 12
#p a ni, 12
#p ala tan, 12
#p ala pali, 12
#p ala moku, 12
#p ala jo, 12
#p ala awen, 12
#p wile weka, 11
#p wile mi, 11
#p weka la, 11
#p wan pi, 11
#p toki musi, 11
#p tawa sijelo, 11
#p tawa lupa, 11
#p tawa kala, 11
#p taso tenpo, 11
#p taso ni, 11
#p tan tomo, 11
#p tan ilo, 11
#p soweli en, 11
#p soweli ante, 11
#p sona la, 11
#p sike lon, 11
#p seme a, 11
#p sama jan, 11
#p pini li, 11
#p pilin ala, 11
#p pi lawa, 11
#p pali mute, 11
#p pali lon, 11
#p ona pi, 11
#p ona kepeken, 11
#p o kalama, 11
#p noka sina, 11
#p noka mi, 11
#p ni taso, 11
#p ni pi, 11
#p nimi namako, 11
#p nasin pona, 11
#p nasin mi, 11
#p musi taso, 11
#p moku ni, 11
#p meli mi, 11
#p mama sina, 11
#p lukin lon, 11
#p li unpa, 11
#p li sin, 11
#p li oko, 11
#p li loje, 11
#p lili lon, 11
#p lili e, 11
#p lawa sina, 11
#p la ilo, 11
#p kon pi, 11
#p kama loje, 11
#p kama jan, 11
#p kama ante, 11
#p jan sin, 11
#p ilo suno, 11
#p ijo ni, 11
#p e wawa, 11
#p e supa, 11
#p esun e, 11
#p e seli, 11
#p e noka, 11
#p e nena, 11
#p e monsi, 11
#p e lape, 11
#p a li, 11
#p ale tawa, 11
#p ale o, 11
#p ala o, 11
#p akesi ni, 11
#p wile musi, 10
#p wile alasa, 10
#p weka lon, 10
#p waso ni, 10
#p wan lon, 10
#p tu la, 10
#p tomo wawa, 10
#p tomo lili, 10
#p tenpo lete, 10
#p telo pi, 10
#p tawa pona, 10
#p tawa o, 10
#p tawa ilo, 10
#p taso soweli, 10
#p tan soweli, 10
#p tan pilin, 10
#p suwi mute, 10
#p suwi li, 10
#p suli a, 10
#p soweli la, 10
#p sona lon, 10
#p sitelen li, 10
#p sin la, 10
#p sina sama, 10
#p sina kin, 10
#p sike li, 10
#p sijelo pi, 10
#p pona sina, 10
#p poki e, 10
#p pi tawa, 10
#p pini suli, 10
#p pimeja ni, 10
#p pimeja la, 10
#p pi kili, 10
#p pi kalama, 10
#p pali ni, 10
#p o utala, 10
#p o sitelen, 10
#p o olin, 10
#p o alasa, 10
#p o ala, 10
#p nena sinpin, 10
#p nasa ala, 10
#p nanpa luka, 10
#p mute o, 10
#p musi mute, 10
#p monsi pi, 10
#p monsi mi, 10
#p ma mi, 10
#p lon ale, 10
#p li wan, 10
#p li sewi, 10
#p lili ona, 10
#p li kiwen, 10
#p lape pona, 10
#p lape li, 10
#p lape la, 10
#p la lipu, 10
#p la kon, 10
#p kute mi, 10
#p kili loje, 10
#p ken ike, 10
#p kama wawa, 10
#p kama lukin, 10
#p kama li, 10
#p jan wan, 10
#p jan utala, 10
#p jan en, 10
#p ilo tawa, 10
#p ilo mi, 10
#p ijo lon, 10
#p e wan, 10
#p esun li, 10
#p en mije, 10
#p ala weka, 10
#p ala mi, 10
#p ala kepeken, 10
#p a a, 10
#p wile unpa, 9
#p wile pilin, 9
#p wile la, 9
#p waso o, 9
#p uta sina, 9
#p unpa li, 9
#p tomo pona, 9
#p toki sama, 9
#p toki la, 9
#p telo la, 9
#p tawa uta, 9
#p tawa supa, 9
#p tawa sinpin, 9
#p tawa la, 9
#p taso sina, 9
#p tan wile, 9
#p tan tenpo, 9
#p suwi tawa, 9
#p suno ale, 9
#p sin tawa, 9
#p sin lon, 9
#p sina weka, 9
#p sina pini, 9
#p sina pakala, 9
#p sina anu, 9
#p sike mute, 9
#p sama nimi, 9
#p pu li, 9
#p pona kin, 9
#p poki len, 9
#p poka telo, 9
#p pi musi, 9
#p pimeja lon, 9
#p pimeja ale, 9
#p pi mani, 9
#p pilin utala, 9
#p pilin musi, 9
#p pi ijo, 9
#p ona sama, 9
#p o moli, 9
#p o luka, 9
#p noka ona, 9
#p ni o, 9
#p nasin tawa, 9
#p nasin sewi, 9
#p nasin ante, 9
#p mute tan, 9
#p mute ale, 9
#p musi la, 9
#p musi ala, 9
#p moku lon, 9
#p mi sama, 9
#p mi mi, 9
#p meli en, 9
#p ma taso, 9
#p mama pi, 9
#p lukin pona, 9
#p lon tawa, 9
#p lon suno, 9
#p lon sina, 9
#p lon mi, 9
#p lon lawa, 9
#p lon e, 9
#p li sitelen, 9
#p li sina, 9
#p lipu mi, 9
#p li nimi, 9
#p li nena, 9
#p li mi, 9
#p lili ni, 9
#p la suno, 9
#p la seme, 9
#p la kala, 9
#p kule ni, 9
#p kule mute, 9
#p ko pan, 9
#p kepeken uta, 9
#p kepeken noka, 9
#p kepeken lipu, 9
#p ken moli, 9
#p kama nasa, 9
#p kama moli, 9
#p kala suli, 9
#p kalama suli, 9
#p kalama pi, 9
#p kalama li, 9
#p jan anu, 9
#p jaki li, 9
#p ike pi, 9
#p ike mi, 9
#p ike lili, 9
#p ijo ala, 9
#p e unpa, 9
#p e tu, 9
#p en soweli, 9
#p en sina, 9
#p e mun, 9
#p e lili, 9
#p e akesi, 9
#p awen pona, 9
#p awen pi, 9
#p ante pi, 9
#p anpa pi, 9
#p ala pilin, 9
#p akesi suli, 9
#p wile jan, 8
#p wawa tawa, 8
#p uta mi, 8
#p tu pi, 8
#p toki ona, 8
#p tenpo mun, 8
#p tenpo la, 8
#p tenpo ali, 8
#p telo wawa, 8
#p telo loje, 8
#p telo lete, 8
#p tawa linja, 8
#p tawa esun, 8
#p taso lon, 8
#p tan telo, 8
#p tan sike, 8
#p tan poki, 8
#p tan pali, 8
#p suno la, 8
#p suli mi, 8
#p soweli ike, 8
#p soweli ale, 8
#p sitelen musi, 8
#p sinpin ona, 8
#p sina ike, 8
#p sina ante, 8
#p sina a, 8
#p selo mi, 8
#p sama mi, 8
#p pu taso, 8
#p pona ona, 8
#p poki telo, 8
#p pi supa, 8
#p pipi lili, 8
#p pini ala, 8
#p pilin ona, 8
#p pi kule, 8
#p pi kon, 8
#p pi ike, 8
#p pi awen, 8
#p pi ante, 8
#p pi akesi, 8
#p o wawa, 8
#p o ken, 8
#p nimi mi, 8
#p nimi ale, 8
#p nasin lon, 8
#p nasa lili, 8
#p nanpa e, 8
#p mute taso, 8
#p musi tawa, 8
#p monsi sina, 8
#p moku mi, 8
#p moku la, 8
#p mi ali, 8
#p ma seme, 8
#p mama meli, 8
#p mama mama, 8
#p lupa lukin, 8
#p lukin sina, 8
#p lukin pi, 8
#p luka tawa, 8
#p lon tan, 8
#p lon sona, 8
#p lon sike, 8
#p lon kon, 8
#p linja pi, 8
#p li ilo, 8
#p lawa lon, 8
#p la sijelo, 8
#p la kulupu, 8
#p la akesi, 8
#p kule seme, 8
#p kule e, 8
#p kon olin, 8
#p ko li, 8
#p kiwen pi, 8
#p kili tawa, 8
#p kili lili, 8
#p kepeken tomo, 8
#p ken pakala, 8
#p kasi ike, 8
#p kama poka, 8
#p jan lon, 8
#p jan kin, 8
#p insa mi, 8
#p ilo sitelen, 8
#p ike lon, 8
#p ijo sin, 8
#p ijo ike, 8
#p ijo ale, 8
#p e uta, 8
#p e pi, 8
#p e namako, 8
#p awen la, 8
#p awen ala, 8
#p a sina, 8
#p ante lon, 8
#p anpa tan, 8
#p ale sina, 8
#p ale lon, 8
#p ala taso, 8
#p ala lape, 8
#p wile utala, 7
#p wile pi, 7
#p wawa pi, 7
#p wawa a, 7
#p waso lon, 7
#p uta pi, 7
#p uta ona, 7
#p unpa ala, 7
#p tu e, 7
#p tomo sona, 7
#p toki taso, 7
#p toki ike, 7
#p toki ante, 7
#p telo tawa, 7
#p telo tan, 7
#p telo mute, 7
#p telo mi, 7
#p supa monsi, 7
#p supa moku, 7
#p suno pi, 7
#p suno mute, 7
#p suno e, 7
#p soweli pona, 7
#p sona tawa, 7
#p sona tan, 7
#p sona sina, 7
#p sinpin sina, 7
#p sin pi, 7
#p sike pi, 7
#p sijelo ona, 7
#p sewi o, 7
#p sewi e, 7
#p seli mute, 7
#p seli la, 7
#p sama ona, 7
#p sama lon, 7
#p pi wawa, 7
#p pi waso, 7
#p pi sijelo, 7
#p pi sewi, 7
#p pi selo, 7
#p pi poki, 7
#p pi poka, 7
#p pipi ni, 7
#p pi pana, 7
#p pilin tawa, 7
#p pilin pakala, 7
#p pilin li, 7
#p pi kiwen, 7
#p pi ale, 7
#p pan suwi, 7
#p pali namako, 7
#p pakala mi, 7
#p o pu, 7
#p open la, 7
#p ona en, 7
#p ona anu, 7
#p ona ale, 7
#p o musi, 7
#p oko pi, 7
#p nimi sina, 7
#p nimi lon, 7
#p nasin sina, 7
#p nasa mute, 7
#p nasa e, 7
#p nanpa mute, 7
#p mute ike, 7
#p musi kepeken, 7
#p mu mu, 7
#p moku tawa, 7
#p moku sina, 7
#p mi anu, 7
#p mi ala, 7
#p ma pona, 7
#p mani mi, 7
#p mani li, 7
#p lukin taso, 7
#p lukin ona, 7
#p lukin mute, 7
#p lon open, 7
#p lon noka, 7
#p lon linja, 7
#p lon len, 7
#p li tu, 7
#p li tomo, 7
#p li telo, 7
#p lipu tawa, 7
#p lipu pu, 7
#p lipu mute, 7
#p li pimeja, 7
#p linja li, 7
#p lili tan, 7
#p li li, 7
#p la waso, 7
#p lawa jan, 7
#p la tomo, 7
#p la toki, 7
#p la pilin, 7
#p la olin, 7
#p la mun, 7
#p la lupa, 7
#p la li, 7
#p la kili, 7
#p kulupu esun, 7
#p kin e, 7
#p kili mi, 7
#p kepeken supa, 7
#p kepeken sona, 7
#p kepeken sitelen, 7
#p kepeken palisa, 7
#p kepeken nena, 7
#p kepeken kalama, 7
#p ken pilin, 7
#p ken moku, 7
#p kasi lon, 7
#p kama wan, 7
#p kama open, 7
#p kalama wawa, 7
#p jan ona, 7
#p jan nasa, 7
#p jan la, 7
#p jan alasa, 7
#p ilo lukin, 7
#p ike ona, 7
#p ike ni, 7
#p ijo la, 7
#p ijo ante, 7
#p a o, 7
#p anu jan, 7
#p anpa lon, 7
#p a lon, 7
#p ale mi, 7
#p alasa weka, 7
#p ala pana, 7
#p ala ona, 7
#p a e, 7
#p wile pona, 6
#p wile mute, 6
#p wile kute, 6
#p wile kepeken, 6
#p wawa tan, 6
#p wawa lon, 6
#p wawa en, 6
#p waso la, 6
#p wan sijelo, 6
#p uta li, 6
#p utala ala, 6
#p tomo esun, 6
#p tomo ante, 6
#p toki tan, 6
#p toki jan, 6
#p tenpo wan, 6
#p tenpo seli, 6
#p tenpo namako, 6
#p tenpo musi, 6
#p tenpo lon, 6
#p tenpo lape, 6
#p tenpo ante, 6
#p telo walo, 6
#p telo ni, 6
#p tawa toki, 6
#p tawa tenpo, 6
#p tawa pilin, 6
#p tawa noka, 6
#p tawa mute, 6
#p tawa monsi, 6
#p tawa meli, 6
#p tawa lukin, 6
#p tawa lili, 6
#p tawa lawa, 6
#p tawa kute, 6
#p tawa kasi, 6
#p taso pi, 6
#p taso nimi, 6
#p taso nasin, 6
#p tan uta, 6
#p tan suno, 6
#p tan lupa, 6
#p tan len, 6
#p tan kon, 6
#p suwi mi, 6
#p suwi la, 6
#p suwi ala, 6
#p suwi a, 6
#p suno mi, 6
#p suno en, 6
#p suli sina, 6
#p soweli o, 6
#p sona toki, 6
#p sona lili, 6
#p sitelen lape, 6
#p sinpin li, 6
#p sina moli, 6
#p sewi ona, 6
#p sewi ni, 6
#p sewi la, 6
#p seme tan, 6
#p seme pi, 6
#p sama telo, 6
#p sama nasin, 6
#p sama li, 6
#p sama la, 6
#p pona kepeken, 6
#p pona en, 6
#p pi ona, 6
#p pi nena, 6
#p pi moku, 6
#p pi mama, 6
#p pi lupa, 6
#p pi luka, 6
#p pilin wawa, 6
#p pilin tan, 6
#p pilin pi, 6
#p pana tawa, 6
#p pana lukin, 6
#p palisa pi, 6
#p palisa luka, 6
#p pali len, 6
#p pakala la, 6
#p o telo, 6
#p o supa, 6
#p open sin, 6
#p open ala, 6
#p ona mute, 6
#p o mu, 6
#p olin mute, 6
#p o len, 6
#p o esun, 6
#p o ante, 6
#p noka li, 6
#p nimi wan, 6
#p nimi nanpa, 6
#p ni mi, 6
#p ni kin, 6
#p nena li, 6
#p nena e, 6
#p nasin wan, 6
#p nasa lon, 6
#p mu wawa, 6
#p mute pona, 6
#p mute ni, 6
#p mute mi, 6
#p moli lon, 6
#p moli la, 6
#p moku taso, 6
#p moku lili, 6
#p mi wan, 6
#p mi pini, 6
#p mi open, 6
#p mi musi, 6
#p mi lawa, 6
#p mije ni, 6
#p mi a, 6
#p meli pi, 6
#p meli ni, 6
#p mani pi, 6
#p mama mije, 6
#p ma kili, 6
#p ma en, 6
#p lukin sama, 6
#p lukin a, 6
#p luka la, 6
#p lon weka, 6
#p lon sitelen, 6
#p lon selo, 6
#p lon musi, 6
#p lon kin, 6
#p lon kasi, 6
#p lon esun, 6
#p li pu, 6
#p li palisa, 6
#p li nanpa, 6
#p li meli, 6
#p li ko, 6
#p li anu, 6
#p lete la, 6
#p len loje, 6
#p lape e, 6
#p la musi, 6
#p la moku, 6
#p la mama, 6
#p la kalama, 6
#p kute pona, 6
#p kulupu lawa, 6
#p kulupu la, 6
#p kule ala, 6
#p kon sewi, 6
#p kon kepeken, 6
#p kili kiwen, 6
#p kepeken kasi, 6
#p ken li, 6
#p kasi sina, 6
#p kasi pi, 6
#p kasi mi, 6
#p kasi e, 6
#p kama walo, 6
#p kama pi, 6
#p kama jaki, 6
#p kama e, 6
#p kalama toki, 6
#p kalama ni, 6
#p kalama lili, 6
#p kalama ike, 6
#p kalama e, 6
#p jan tan, 6
#p jan sama, 6
#p jan poka, 6
#p jan nanpa, 6
#p jan musi, 6
#p jan kepeken, 6
#p jaki e, 6
#p ilo moku, 6
#p ilo alasa, 6
#p ike ale, 6
#p ijo wan, 6
#p ijo musi, 6
#p ijo mi, 6
#p esun pi, 6
#p en ilo, 6
#p e mu, 6
#p e mije, 6
#p e kama, 6
#p e jaki, 6
#p anu nimi, 6
#p ante tan, 6
#p ante mute, 6
#p ante kule, 6
#p anpa la, 6
#p ale ale, 6
#p ala sin, 6
#p alasa li, 6
#p ala pi, 6
#p ala moli, 6
#p a ike, 6
#p wile ni, 5
#p wile awen, 5
#p wile ante, 5
#p weka tawa, 5
#p weka pi, 5
#p wawa sina, 5
#p wawa ilo, 5
#p waso mute, 5
#p walo lon, 5
#p uta suwi, 5
#p utala la, 5
#p tu taso, 5
#p tomo toki, 5
#p tomo sin, 5
#p tomo lon, 5
#p tomo ale, 5
#p toki mute, 5
#p tenpo tawa, 5
#p tenpo sama, 5
#p tenpo pona, 5
#p tenpo ilo, 5
#p telo seli, 5
#p tawa tan, 5
#p tawa sona, 5
#p tawa pali, 5
#p tawa nimi, 5
#p tawa nena, 5
#p tawa luka, 5
#p tawa lipu, 5
#p tawa kon, 5
#p tawa awen, 5
#p taso waso, 5
#p taso tan, 5
#p taso o, 5
#p taso ala, 5
#p tan supa, 5
#p tan sijelo, 5
#p tan nasin, 5
#p tan monsi, 5
#p tan luka, 5
#p tan lipu, 5
#p tan insa, 5
#p tan esun, 5
#p suwi o, 5
#p suwi ni, 5
#p supa pi, 5
#p supa li, 5
#p suno tawa, 5
#p suno open, 5
#p suli luka, 5
#p suli kepeken, 5
#p soweli tomo, 5
#p soweli suwi, 5
#p soweli awen, 5
#p soweli ala, 5
#p sona suli, 5
#p sitelen kepeken, 5
#p sinpin mi, 5
#p sinpin lupa, 5
#p sina lawa, 5
#p sin ala, 5
#p sina jaki, 5
#p sina ale, 5
#p sike nanpa, 5
#p sewi tawa, 5
#p seme mi, 5
#p selo ona, 5
#p selo li, 5
#p pu la, 5
#p pona suli, 5
#p pona o, 5
#p pona ale, 5
#p poki pi, 5
#p poki moku, 5
#p poki lili, 5
#p poka seli, 5
#p poka li, 5
#p poka la, 5
#p pi weka, 5
#p pilin suwi, 5
#p pilin lape, 5
#p pilin la, 5
#p pilin jaki, 5
#p pi linja, 5
#p pi len, 5
#p pi kute, 5
#p pan telo, 5
#p pan tawa, 5
#p palisa suli, 5
#p pali sama, 5
#p pali ona, 5
#p o tenpo, 5
#p open tawa, 5
#p open pi, 5
#p o nasa, 5
#p o nanpa, 5
#p ona kin, 5
#p ona a, 5
#p olin tu, 5
#p olin pi, 5
#p noka ala, 5
#p nimi seme, 5
#p nimi en, 5
#p ni a, 5
#p nena suli, 5
#p nena mama, 5
#p nasin toki, 5
#p nasin ona, 5
#p nasin lawa, 5
#p nasa a, 5
#p nanpa sin, 5
#p nanpa pu, 5
#p nanpa o, 5
#p namako li, 5
#p mute sin, 5
#p mute luka, 5
#p musi sin, 5
#p musi sama, 5
#p musi pona, 5
#p mun mute, 5
#p mun lili, 5
#p mu mute, 5
#p monsi soweli, 5
#p moli tan, 5
#p moku tan, 5
#p moku pi, 5
#p moku pan, 5
#p mi utala, 5
#p mi kule, 5
#p mi kalama, 5
#p mije sina, 5
#p mije pi, 5
#p mije en, 5
#p ma tenpo, 5
#p mani tawa, 5
#p mani ala, 5
#p mama o, 5
#p ma ike, 5
#p lupa ni, 5
#p lukin tan, 5
#p luka ante, 5
#p luka ala, 5
#p lon moku, 5
#p loje jelo, 5
#p lipu sina, 5
#p lipu lili, 5
#p linja ni, 5
#p li namako, 5
#p li mama, 5
#p lili pona, 5
#p lili a, 5
#p li kulupu, 5
#p li kon, 5
#p li insa, 5
#p len lili, 5
#p len lawa, 5
#p len laso, 5
#p len la, 5
#p lawa meli, 5
#p lape taso, 5
#p la mije, 5
#p la lawa, 5
#p la kiwen, 5
#p la ike, 5
#p kute suli, 5
#p kule loje, 5
#p kule kon, 5
#p kule ante, 5
#p ko suwi, 5
#p kon sama, 5
#p ko ni, 5
#p ko ma, 5
#p kepeken mani, 5
#p kepeken kule, 5
#p kepeken e, 5
#p ken sitelen, 5
#p ken olin, 5
#p ken lape, 5
#p ken jo, 5
#p ken awen, 5
#p kasi tawa, 5
#p kasi mute, 5
#p kama pini, 5
#p kama ken, 5
#p kama jelo, 5
#p kala o, 5
#p kala mute, 5
#p kalama uta, 5
#p kala ma, 5
#p jan suwi, 5
#p insa li, 5
#p insa kepeken, 5
#p ilo sin, 5
#p ilo nasa, 5
#p ilo kalama, 5
#p ike sina, 5
#p ike lukin, 5
#p ijo tan, 5
#p ijo suli, 5
#p ijo nasa, 5
#p esun ala, 5
#p e o, 5
#p en nimi, 5
#p en ma, 5
#p e anpa, 5
#p awen wile, 5
#p awen sona, 5
#p awen lukin, 5
#p awen lili, 5
#p anu e, 5
#p ante ala, 5
#p anpa tawa, 5
#p ale tan, 5
#p ala telo, 5
#p ala sina, 5
#p alasa pi, 5
#p ala ni, 5
#p ala ike, 5
#p ala ante, 5
#p wile taso, 4
#p wile ona, 4
#p wile olin, 4
#p wile ale, 4
#p weka wawa, 4
#p wawa suno, 4
#p wawa ona, 4
#p wawa nasa, 4
#p waso suli, 4
#p waso mi, 4
#p wan tu, 4
#p wan olin, 4
#p wan en, 4
#p walo tan, 4
#p walo pi, 4
#p walo la, 4
#p walo e, 4
#p uta la, 4
#p unpa la, 4
#p tu tan, 4
#p tomo lawa, 4
#p tomo lape, 4
#p toki uta, 4
#p toki suwi, 4
#p toki suli, 4
#p toki o, 4
#p toki ilo, 4
#p tenpo weka, 4
#p tenpo sina, 4
#p tenpo esun, 4
#p telo lon, 4
#p telo kili, 4
#p telo ilo, 4
#p telo en, 4
#p tawa taso, 4
#p tawa sin, 4
#p tawa seme, 4
#p tawa seli, 4
#p tawa sama, 4
#p tawa mun, 4
#p tawa mije, 4
#p tawa ko, 4
#p tawa anu, 4
#p taso tawa, 4
#p taso kepeken, 4
#p taso ken, 4
#p taso ijo, 4
#p tan selo, 4
#p tan seli, 4
#p tan pakala, 4
#p tan olin, 4
#p tan nena, 4
#p tan moli, 4
#p tan mama, 4
#p tan lukin, 4
#p tan ko, 4
#p tan kasi, 4
#p tan ijo, 4
#p suwi pi, 4
#p suwi lon, 4
#p suwi kepeken, 4
#p supa pali, 4
#p supa ni, 4
#p suno wawa, 4
#p suno wan, 4
#p suno pini, 4
#p suno nanpa, 4
#p suno mun, 4
#p suli wan, 4
#p suli o, 4
#p suli nanpa, 4
#p soweli sina, 4
#p soweli sama, 4
#p soweli e, 4
#p soweli alasa, 4
#p sona ona, 4
#p sona musi, 4
#p sitelen sin, 4
#p sitelen lon, 4
#p sin o, 4
#p sin mute, 4
#p sin mi, 4
#p sina sitelen, 4
#p sina pi, 4
#p sina ona, 4
#p sina musi, 4
#p sina mi, 4
#p sike waso, 4
#p sike tu, 4
#p sike suli, 4
#p sike sin, 4
#p sijelo sewi, 4
#p sewi tan, 4
#p sewi mi, 4
#p sewi lon, 4
#p seme tawa, 4
#p sama waso, 4
#p sama tawa, 4
#p sama suno, 4
#p sama pilin, 4
#p sama e, 4
#p pona jan, 4
#p poki suli, 4
#p poki mi, 4
#p poki li, 4
#p poki kiwen, 4
#p poka tomo, 4
#p poka lili, 4
#p pi pipi, 4
#p pipi mute, 4
#p pi palisa, 4
#p pini weka, 4
#p pini tawa, 4
#p pini lon, 4
#p pimeja mute, 4
#p pimeja kama, 4
#p pi lon, 4
#p pilin wan, 4
#p pilin lili, 4
#p pilin jan, 4
#p pi laso, 4
#p pi ko, 4
#p pi alasa, 4
#p pan ni, 4
#p pan lon, 4
#p pan e, 4
#p pana sona, 4
#p pana sin, 4
#p pali sina, 4
#p palisa tu, 4
#p palisa ni, 4
#p palisa kasi, 4
#p palisa jelo, 4
#p pali moku, 4
#p pali lili, 4
#p pali ike, 4
#p pakala tan, 4
#p pakala a, 4
#p o waso, 4
#p o soweli, 4
#p o sewi, 4
#p o seme, 4
#p o seli, 4
#p open li, 4
#p ona taso, 4
#p olin taso, 4
#p olin tan, 4
#p o lawa, 4
#p o kulupu, 4
#p oko sina, 4
#p oko li, 4
#p o jan, 4
#p o ike, 4
#p noka tan, 4
#p ni sina, 4
#p nimi taso, 4
#p nimi tan, 4
#p nimi la, 4
#p nimi anu, 4
#p ni en, 4
#p nena kute, 4
#p nasin weka, 4
#p nasin olin, 4
#p nasin mani, 4
#p nasin la, 4
#p nasin jan, 4
#p nasa tan, 4
#p nasa ni, 4
#p nasa mi, 4
#p nasa la, 4
#p nanpa tawa, 4
#p nanpa suli, 4
#p nanpa seme, 4
#p namako lon, 4
#p mute lili, 4
#p mute kin, 4
#p mute en, 4
#p mute anu, 4
#p musi sina, 4
#p musi o, 4
#p musi kin, 4
#p musi ante, 4
#p mu pi, 4
#p mu ala, 4
#p monsi tomo, 4
#p moku seme, 4
#p moku ale, 4
#p mi seli, 4
#p mi luka, 4
#p mije mi, 4
#p meli sina, 4
#p ma weka, 4
#p ma esun, 4
#p ma e, 4
#p lupa lon, 4
#p lupa lili, 4
#p lukin sin, 4
#p lukin kepeken, 4
#p luka sike, 4
#p luka ni, 4
#p lon soweli, 4
#p lon sijelo, 4
#p lon pi, 4
#p lon olin, 4
#p loje pi, 4
#p loje ni, 4
#p li waso, 4
#p li sinpin, 4
#p lipu sin, 4
#p lipu nimi, 4
#p lipu lon, 4
#p lipu la, 4
#p li poki, 4
#p li noka, 4
#p linja loje, 4
#p li ni, 4
#p li mani, 4
#p lili tu, 4
#p lili mi, 4
#p lili luka, 4
#p li esun, 4
#p li ale, 4
#p len suli, 4
#p len kepeken, 4
#p lawa ala, 4
#p laso lili, 4
#p la sitelen, 4
#p la pona, 4
#p la poki, 4
#p la pipi, 4
#p lape ona, 4
#p la nanpa, 4
#p la luka, 4
#p la loje, 4
#p la kasi, 4
#p kute pi, 4
#p kute li, 4
#p kulupu suli, 4
#p kulupu musi, 4
#p kulupu mi, 4
#p ko walo, 4
#p ko pi, 4
#p kon mi, 4
#p kiwen suli, 4
#p kiwen ni, 4
#p kiwen lon, 4
#p kili pimeja, 4
#p kili palisa, 4
#p kili mute, 4
#p kili laso, 4
#p kili e, 4
#p kepeken ni, 4
#p kepeken nanpa, 4
#p kepeken ko, 4
#p ken taso, 4
#p ken mu, 4
#p ken lawa, 4
#p kama telo, 4
#p kama mi, 4
#p kama kulupu, 4
#p kala sina, 4
#p kalama sin, 4
#p kalama noka, 4
#p kalama ala, 4
#p jan taso, 4
#p jan lukin, 4
#p jan lipu, 4
#p jan kule, 4
#p jan ken, 4
#p jaki la, 4
#p jaki ala, 4
#p insa ona, 4
#p ilo sina, 4
#p ilo kepeken, 4
#p ike o, 4
#p ijo seme, 4
#p esun ni, 4
#p e sama, 4
#p e pimeja, 4
#p en telo, 4
#p en mun, 4
#p en mu, 4
#p en meli, 4
#p e la, 4
#p e e, 4
#p e ante, 4
#p e ali, 4
#p e ala, 4
#p awen tan, 4
#p awen pilin, 4
#p awen mi, 4
#p awen luka, 4
#p awen kama, 4
#p a tawa, 4
#p a pakala, 4
#p ali ala, 4
#p ale ona, 4
#p ale mute, 4
#p ale e, 4
#p ala suli, 4
#p ala sitelen, 4
#p alasa tawa, 4
#p alasa mute, 4
#p ala sama, 4
#p alasa luka, 4
#p alasa kala, 4
#p ala pakala, 4
#p ala olin, 4
#p ala nimi, 4
#p ala ma, 4
#p ala ilo, 4
#p akesi pi, 4
#p akesi mi, 4
#p akesi lili, 4
#p a jan, 4
#p wile wawa, 3
#p wile telo, 3
#p wile suli, 3
#p wile sitelen, 3
#p wile pini, 3
#p wile pakala, 3
#p wile li, 3
#p wile kalama, 3
#p wile jo, 3
#p wile esun, 3
#p weka o, 3
#p weka li, 3
#p wawa o, 3
#p waso pi, 3
#p waso kepeken, 3
#p wan ona, 3
#p wan o, 3
#p utala tawa, 3
#p utala tan, 3
#p utala pona, 3
#p utala ni, 3
#p utala lon, 3
#p uta e, 3
#p unpa lukin, 3
#p unpa e, 3
#p tu ale, 3
#p tomo o, 3
#p tomo mute, 3
#p tomo musi, 3
#p tomo kepeken, 3
#p toki wawa, 3
#p toki olin, 3
#p toki nasa, 3
#p toki ma, 3
#p toki len, 3
#p toki awen, 3
#p toki ale, 3
#p tenpo wawa, 3
#p tenpo tu, 3
#p tenpo sin, 3
#p tenpo sewi, 3
#p tenpo mi, 3
#p tenpo ike, 3
#p telo taso, 3
#p telo sina, 3
#p telo sijelo, 3
#p telo pimeja, 3
#p telo ona, 3
#p telo mama, 3
#p telo linja, 3
#p telo lili, 3
#p telo kasi, 3
#p telo jelo, 3
#p telo ala, 3
#p tawa wan, 3
#p tawa selo, 3
#p tawa olin, 3
#p tawa len, 3
#p tawa ijo, 3
#p tawa ale, 3
#p taso toki, 3
#p taso sona, 3
#p taso pali, 3
#p taso lipu, 3
#p taso len, 3
#p taso lape, 3
#p tan weka, 3
#p tan poka, 3
#p tan pi, 3
#p tan oko, 3
#p tan nimi, 3
#p tan moku, 3
#p tan lon, 3
#p tan lawa, 3
#p tan lape, 3
#p tan kama, 3
#p tan kalama, 3
#p tan ike, 3
#p tan ala, 3
#p supa poki, 3
#p supa lon, 3
#p suno seli, 3
#p suno pona, 3
#p suno o, 3
#p suno lon, 3
#p suno laso, 3
#p suli tan, 3
#p suli sama, 3
#p suli ona, 3
#p soweli wawa, 3
#p soweli walo, 3
#p soweli tan, 3
#p soweli mute, 3
#p soweli mani, 3
#p soweli ma, 3
#p soweli kepeken, 3
#p soweli anu, 3
#p sona sin, 3
#p sona pali, 3
#p sona o, 3
#p sona nanpa, 3
#p sona kepeken, 3
#p sona ale, 3
#p sitelen sitelen, 3
#p sitelen mi, 3
#p sitelen lukin, 3
#p sitelen la, 3
#p sitelen ale, 3
#p sinpin sitelen, 3
#p sinpin nanpa, 3
#p sin ni, 3
#p sina wawa, 3
#p sina wan, 3
#p sina suwi, 3
#p sina sina, 3
#p sina seme, 3
#p sina ni, 3
#p sina mu, 3
#p sina luka, 3
#p sina lape, 3
#p sina kule, 3
#p sina e, 3
#p sike wile, 3
#p sike tawa, 3
#p sike suno, 3
#p sike ni, 3
#p sike mama, 3
#p sike ma, 3
#p sike ala, 3
#p sijelo soweli, 3
#p sijelo ni, 3
#p sijelo kepeken, 3
#p sijelo ante, 3
#p sijelo ale, 3
#p sewi taso, 3
#p sewi pimeja, 3
#p sewi luka, 3
#p sewi lili, 3
#p sewi lawa, 3
#p sewi kon, 3
#p sewi kepeken, 3
#p seme jan, 3
#p selo soweli, 3
#p selo e, 3
#p seli suli, 3
#p seli sewi, 3
#p seli pi, 3
#p seli lon, 3
#p seli anu, 3
#p sama sitelen, 3
#p sama seli, 3
#p sama pipi, 3
#p sama pi, 3
#p sama nanpa, 3
#p sama mute, 3
#p sama mun, 3
#p sama ma, 3
#p sama ko, 3
#p sama kili, 3
#p sama kepeken, 3
#p pona sin, 3
#p pona sijelo, 3
#p pona pilin, 3
#p pona nasa, 3
#p pona moku, 3
#p pona ali, 3
#p poki tawa, 3
#p poki sina, 3
#p poki kepeken, 3
#p poki jaki, 3
#p poka walo, 3
#p poka suli, 3
#p poka pimeja, 3
#p poka lete, 3
#p pipi suli, 3
#p pi noka, 3
#p pini taso, 3
#p pini mute, 3
#p pini mi, 3
#p pi mije, 3
#p pimeja pini, 3
#p pimeja en, 3
#p pilin taso, 3
#p pilin seli, 3
#p pilin nasa, 3
#p pilin mute, 3
#p pilin lon, 3
#p pi kala, 3
#p pi insa, 3
#p pan la, 3
#p pana wawa, 3
#p pana pi, 3
#p pali wawa, 3
#p pali taso, 3
#p palisa kili, 3
#p pali pona, 3
#p pali la, 3
#p pali ale, 3
#p pakala sama, 3
#p o tomo, 3
#p o suno, 3
#p o sama, 3
#p open tan, 3
#p open pali, 3
#p open mi, 3
#p open kama, 3
#p o noka, 3
#p ona e, 3
#p o ma, 3
#p olin suli, 3
#p olin pona, 3
#p o jaki, 3
#p noka pi, 3
#p noka ni, 3
#p nimi sewi, 3
#p nimi pona, 3
#p nimi oko, 3
#p nimi ike, 3
#p nimi ante, 3
#p ni ala, 3
#p nena pi, 3
#p nena ni, 3
#p nena lon, 3
#p nasin taso, 3
#p nasin suli, 3
#p nasin nasa, 3
#p nasin moku, 3
#p nasin ike, 3
#p nasin e, 3
#p nasin a, 3
#p nasa pi, 3
#p nasa musi, 3
#p nasa lukin, 3
#p nanpa toki, 3
#p nanpa pona, 3
#p nanpa pini, 3
#p nanpa ni, 3
#p nanpa la, 3
#p nanpa en, 3
#p namako pona, 3
#p namako ni, 3
#p mute tu, 3
#p mu tan, 3
#p mu soweli, 3
#p musi sike, 3
#p musi poka, 3
#p musi a, 3
#p mun o, 3
#p mu li, 3
#p moku suwi, 3
#p moku soweli, 3
#p moku ante, 3
#p mi wawa, 3
#p mi telo, 3
#p mi suli, 3
#p mi pu, 3
#p mi moli, 3
#p mi mije, 3
#p mije anu, 3
#p mi ike, 3
#p mi ante, 3
#p meli o, 3
#p meli lawa, 3
#p meli e, 3
#p meli anu, 3
#p ma tan, 3
#p ma sina, 3
#p ma pan, 3
#p mani la, 3
#p ma mute, 3
#p mama jan, 3
#p mama ala, 3
#p ma anu, 3
#p lukin anu, 3
#p luka wawa, 3
#p luka lon, 3
#p lon wan, 3
#p lon utala, 3
#p lon taso, 3
#p lon sin, 3
#p lon pan, 3
#p lon pali, 3
#p lon oko, 3
#p lon nena, 3
#p lon ko, 3
#p lon kiwen, 3
#p lon anu, 3
#p loje tawa, 3
#p loje tan, 3
#p loje sijelo, 3
#p loje la, 3
#p li selo, 3
#p lipu tenpo, 3
#p li pipi, 3
#p linja wan, 3
#p linja telo, 3
#p linja suli, 3
#p linja sike, 3
#p linja ona, 3
#p linja mute, 3
#p linja monsi, 3
#p li mun, 3
#p lili tenpo, 3
#p lili suwi, 3
#p li lipu, 3
#p lili nanpa, 3
#p lili moku, 3
#p lili loje, 3
#p lili ante, 3
#p li kili, 3
#p li a, 3
#p lete taso, 3
#p lete e, 3
#p len tan, 3
#p len sin, 3
#p len pona, 3
#p len ma, 3
#p len lape, 3
#p la wile, 3
#p lawa wawa, 3
#p la wawa, 3
#p lawa soweli, 3
#p lawa mije, 3
#p lawa la, 3
#p lawa ike, 3
#p la tawa, 3
#p la supa, 3
#p laso ni, 3
#p la sona, 3
#p laso ala, 3
#p la sinpin, 3
#p la selo, 3
#p lape sina, 3
#p lape ni, 3
#p lape mute, 3
#p lape lili, 3
#p la pali, 3
#p la pakala, 3
#p la noka, 3
#p la nena, 3
#p la lili, 3
#p la len, 3
#p la kule, 3
#p la ko, 3
#p la ken, 3
#p la kama, 3
#p kute sina, 3
#p kute ona, 3
#p kulupu sona, 3
#p kulupu sina, 3
#p kulupu ona, 3
#p kulupu olin, 3
#p kulupu nena, 3
#p kule ale, 3
#p kon wawa, 3
#p kon tan, 3
#p kon ona, 3
#p kon nasa, 3
#p kon jaki, 3
#p ko lete, 3
#p ko jaki, 3
#p kiwen walo, 3
#p kiwen e, 3
#p kin o, 3
#p kin a, 3
#p kili suwi, 3
#p kili pona, 3
#p kili ona, 3
#p kepeken telo, 3
#p kepeken sike, 3
#p kepeken kon, 3
#p kepeken kiwen, 3
#p ken wan, 3
#p ken suli, 3
#p ken open, 3
#p ken nanpa, 3
#p ken jan, 3
#p ken alasa, 3
#p kasi taso, 3
#p kasi seli, 3
#p kasi palisa, 3
#p kasi moku, 3
#p kasi kin, 3
#p kasi en, 3
#p kama sewi, 3
#p kama sama, 3
#p kama pimeja, 3
#p kama pilin, 3
#p kama pali, 3
#p kama nanpa, 3
#p kama lete, 3
#p kama laso, 3
#p kama kin, 3
#p kama akesi, 3
#p kama a, 3
#p kala ni, 3
#p kalama ona, 3
#p kalama mi, 3
#p kalama a, 3
#p kala en, 3
#p jo mi, 3
#p jelo taso, 3
#p jelo tan, 3
#p jelo ni, 3
#p jelo lon, 3
#p jelo e, 3
#p jan sina, 3
#p jan moli, 3
#p jan ma, 3
#p jan kute, 3
#p jan e, 3
#p jaki tan, 3
#p jaki pi, 3
#p jaki mi, 3
#p insa poki, 3
#p insa pilin, 3
#p insa luka, 3
#p ilo tan, 3
#p ilo poki, 3
#p ilo musi, 3
#p ilo la, 3
#p ilo kute, 3
#p ilo ike, 3
#p ike taso, 3
#p ike suli, 3
#p ike nanpa, 3
#p ike anu, 3
#p ijo tu, 3
#p ijo taso, 3
#p ijo namako, 3
#p ijo luka, 3
#p ijo loje, 3
#p ijo lili, 3
#p ijo ali, 3
#p e weka, 3
#p esun pini, 3
#p esun len, 3
#p e suli, 3
#p e pini, 3
#p en wawa, 3
#p en walo, 3
#p en tenpo, 3
#p en nasin, 3
#p en luka, 3
#p en lipu, 3
#p en li, 3
#p en kiwen, 3
#p en kili, 3
#p en ike, 3
#p e nasa, 3
#p en akesi, 3
#p e moli, 3
#p e mama, 3
#p e jo, 3
#p e awen, 3
#p awen weka, 3
#p awen taso, 3
#p awen sama, 3
#p awen open, 3
#p awen olin, 3
#p awen o, 3
#p awen kepeken, 3
#p awen ken, 3
#p a tenpo, 3
#p anu telo, 3
#p anu sitelen, 3
#p anu mije, 3
#p anu ma, 3
#p anu ilo, 3
#p anu ike, 3
#p ante toki, 3
#p ante ona, 3
#p ante ni, 3
#p anpa telo, 3
#p anpa mi, 3
#p ali o, 3
#p ali mi, 3
#p ali lon, 3
#p ali la, 3
#p ale tu, 3
#p ale kepeken, 3
#p ale ante, 3
#p ale ala, 3
#p ale a, 3
#p alasa sona, 3
#p ala poka, 3
#p ala pini, 3
#p ala musi, 3
#p ala kin, 3
#p ala insa, 3
#p akesi waso, 3
#p akesi seli, 3
#p akesi e, 3
#p a ken, 3
#p a ilo, 3
#p wile wan, 2
#p wile tan, 2
#p wile soweli, 2
#p wile poki, 2
#p wile moli, 2
#p wile lawa, 2
#p wile ike, 2
#p wile a, 2
#p weka sona, 2
#p weka ni, 2
#p weka mi, 2
#p weka kepeken, 2
#p weka jaki, 2
#p weka a, 2
#p wawa tenpo, 2
#p wawa ni, 2
#p wawa ike, 2
#p waso walo, 2
#p waso pona, 2
#p waso ona, 2
#p waso kule, 2
#p waso ilo, 2
#p waso en, 2
#p waso alasa, 2
#p wan sina, 2
#p wan namako, 2
#p wan mute, 2
#p wan mi, 2
#p wan anu, 2
#p wan ala, 2
#p walo uta, 2
#p walo sama, 2
#p walo lili, 2
#p uta tawa, 2
#p uta musi, 2
#p utala taso, 2
#p utala sina, 2
#p utala nanpa, 2
#p utala mute, 2
#p utala musi, 2
#p utala lili, 2
#p utala ale, 2
#p unpa taso, 2
#p unpa pi, 2
#p unpa mute, 2
#p unpa lon, 2
#p unpa kin, 2
#p tu tawa, 2
#p tu olin, 2
#p tu luka, 2
#p tu lon, 2
#p tu kepeken, 2
#p tu ala, 2
#p tomo telo, 2
#p tomo taso, 2
#p tomo tan, 2
#p tomo soweli, 2
#p tomo sewi, 2
#p tomo pimeja, 2
#p tomo pali, 2
#p tomo lipu, 2
#p tomo len, 2
#p tomo ilo, 2
#p toki seme, 2
#p toki open, 2
#p toki mama, 2
#p toki luka, 2
#p toki lili, 2
#p toki kin, 2
#p toki a, 2
#p tenpo pali, 2
#p tenpo open, 2
#p tenpo kulupu, 2
#p tenpo jan, 2
#p tenpo alasa, 2
#p telo suwi, 2
#p telo sewi, 2
#p telo pona, 2
#p telo moku, 2
#p telo kepeken, 2
#p telo ale, 2
#p telo a, 2
#p tawa tu, 2
#p tawa pana, 2
#p tawa pakala, 2
#p tawa mama, 2
#p tawa lape, 2
#p tawa kama, 2
#p tawa jaki, 2
#p tawa akesi, 2
#p taso telo, 2
#p taso sitelen, 2
#p taso meli, 2
#p taso mama, 2
#p taso lili, 2
#p taso lawa, 2
#p taso kulupu, 2
#p taso kala, 2
#p taso ike, 2
#p taso awen, 2
#p taso anu, 2
#p tan pona, 2
#p tan mu, 2
#p tan lili, 2
#p tan li, 2
#p tan lete, 2
#p tan kiwen, 2
#p tan ken, 2
#p tan kala, 2
#p tan ante, 2
#p tan anpa, 2
#p suwi tan, 2
#p suwi lukin, 2
#p suwi lili, 2
#p supa mi, 2
#p supa ma, 2
#p supa kepeken, 2
#p suno sin, 2
#p suno lili, 2
#p suno ali, 2
#p suno ala, 2
#p suli tu, 2
#p suli pona, 2
#p suli poka, 2
#p suli namako, 2
#p suli lili, 2
#p suli jan, 2
#p suli ike, 2
#p suli ale, 2
#p soweli tawa, 2
#p soweli sin, 2
#p soweli ona, 2
#p soweli luka, 2
#p soweli lon, 2
#p soweli kasi, 2
#p sona sijelo, 2
#p sona seme, 2
#p sona len, 2
#p sona kalama, 2
#p sona jan, 2
#p sona ike, 2
#p sona en, 2
#p sona a, 2
#p sitelen wan, 2
#p sitelen suli, 2
#p sitelen sina, 2
#p sitelen pana, 2
#p sitelen lili, 2
#p sitelen insa, 2
#p sitelen ante, 2
#p sin tu, 2
#p sin tan, 2
#p sin sina, 2
#p sinpin walo, 2
#p sinpin suno, 2
#p sinpin pona, 2
#p sina sike, 2
#p sina selo, 2
#p sin anu, 2
#p sina meli, 2
#p sina kalama, 2
#p sina esun, 2
#p sina alasa, 2
#p sike walo, 2
#p sike pini, 2
#p sike la, 2
#p sike kule, 2
#p sike ante, 2
#p sike ale, 2
#p sijelo pona, 2
#p sijelo o, 2
#p sijelo loje, 2
#p sijelo la, 2
#p sijelo kasi, 2
#p sewi tomo, 2
#p sewi sina, 2
#p sewi nena, 2
#p sewi anu, 2
#p sewi ala, 2
#p seme sina, 2
#p seme kepeken, 2
#p seme e, 2
#p selo sina, 2
#p selo pan, 2
#p selo ma, 2
#p selo kule, 2
#p selo kiwen, 2
#p selo kili, 2
#p selo jelo, 2
#p seli tawa, 2
#p seli suno, 2
#p sama toki, 2
#p sama soweli, 2
#p sama sike, 2
#p sama palisa, 2
#p sama nena, 2
#p sama lili, 2
#p sama kule, 2
#p sama ale, 2
#p sama akesi, 2
#p pu tawa, 2
#p pu lon, 2
#p pu kin, 2
#p pu ale, 2
#p pona toki, 2
#p pona sama, 2
#p pona ni, 2
#p pona luka, 2
#p pona lili, 2
#p poki sitelen, 2
#p poki mani, 2
#p poki lon, 2
#p poki laso, 2
#p poki kala, 2
#p poka wan, 2
#p poka tu, 2
#p poka nasin, 2
#p poka e, 2
#p poka ante, 2
#p poka ale, 2
#p pi wan, 2
#p pi utala, 2
#p pi uta, 2
#p pi unpa, 2
#p pi tu, 2
#p pi suwi, 2
#p pi sinpin, 2
#p pi sama, 2
#p pipi waso, 2
#p pipi pi, 2
#p pipi o, 2
#p pipi nanpa, 2
#p pi pimeja, 2
#p pipi lon, 2
#p pipi loje, 2
#p pipi kule, 2
#p pipi kon, 2
#p pipi kepeken, 2
#p pipi a, 2
#p pi pan, 2
#p pini tenpo, 2
#p pini sewi, 2
#p pini pona, 2
#p pini ona, 2
#p pini alasa, 2
#p pini a, 2
#p pi namako, 2
#p pimeja taso, 2
#p pimeja pi, 2
#p pimeja anu, 2
#p pi loje, 2
#p pilin seme, 2
#p pilin ni, 2
#p pilin lete, 2
#p pilin kin, 2
#p pilin a, 2
#p pi lete, 2
#p pi ken, 2
#p pi ala, 2
#p pan tan, 2
#p pan sike, 2
#p pan mi, 2
#p pan en, 2
#p pana suli, 2
#p pana pona, 2
#p pana lon, 2
#p pali wile, 2
#p pali tan, 2
#p pali suli, 2
#p pali sin, 2
#p palisa uta, 2
#p palisa seli, 2
#p palisa nanpa, 2
#p palisa lili, 2
#p palisa li, 2
#p palisa laso, 2
#p palisa kiwen, 2
#p palisa ale, 2
#p pali pini, 2
#p pali nasa, 2
#p pali mani, 2
#p pali lipu, 2
#p pali ante, 2
#p pakala tawa, 2
#p pakala pona, 2
#p pakala o, 2
#p pakala lon, 2
#p pakala lili, 2
#p pakala ike, 2
#p o uta, 2
#p o unpa, 2
#p o tu, 2
#p o tan, 2
#p o suli, 2
#p o sike, 2
#p o poki, 2
#p open utala, 2
#p open pu, 2
#p open ona, 2
#p open lon, 2
#p o oko, 2
#p o nimi, 2
#p ona wan, 2
#p ona ante, 2
#p o meli, 2
#p olin tawa, 2
#p olin sona, 2
#p olin sama, 2
#p olin ni, 2
#p olin en, 2
#p o li, 2
#p o lete, 2
#p oko wan, 2
#p oko ona, 2
#p oko lon, 2
#p o kala, 2
#p o ilo, 2
#p o anpa, 2
#p noka wawa, 2
#p noka pakala, 2
#p noka mute, 2
#p noka lili, 2
#p noka kasi, 2
#p noka jelo, 2
#p noka e, 2
#p ni tenpo, 2
#p ni sama, 2
#p nimi suli, 2
#p nimi soweli, 2
#p nimi luka, 2
#p nimi lili, 2
#p nimi kin, 2
#p nimi jan, 2
#p nimi ilo, 2
#p nimi e, 2
#p nimi anpa, 2
#p nimi ali, 2
#p ni kili, 2
#p ni jan, 2
#p nena wawa, 2
#p nena sina, 2
#p nena noka, 2
#p nena mute, 2
#p nena mi, 2
#p nasin unpa, 2
#p nasin telo, 2
#p nasin sona, 2
#p nasin sama, 2
#p nasin pu, 2
#p nasin pana, 2
#p nasin mije, 2
#p nasin meli, 2
#p nasin lape, 2
#p nasin kepeken, 2
#p nasin ijo, 2
#p nasin ale, 2
#p nasa taso, 2
#p nasa seme, 2
#p nasa ona, 2
#p nasa kin, 2
#p nasa kepeken, 2
#p nanpa lon, 2
#p nanpa kin, 2
#p nanpa ale, 2
#p namako tawa, 2
#p namako taso, 2
#p namako pi, 2
#p namako mute, 2
#p namako luka, 2
#p namako e, 2
#p mu waso, 2
#p mute sina, 2
#p mute ona, 2
#p mute kepeken, 2
#p mute jan, 2
#p mute ante, 2
#p mu tawa, 2
#p mu taso, 2
#p mu suwi, 2
#p musi tan, 2
#p musi seme, 2
#p musi kulupu, 2
#p musi ike, 2
#p musi en, 2
#p mu pona, 2
#p mu pipi, 2
#p mun ilo, 2
#p mu mi, 2
#p mu lon, 2
#p monsi lon, 2
#p monsi jan, 2
#p moli pi, 2
#p moli ona, 2
#p moli mi, 2
#p moku o, 2
#p moku kepeken, 2
#p moku anu, 2
#p mi sina, 2
#p mi sike, 2
#p mi sewi, 2
#p mi ona, 2
#p mi nasa, 2
#p mi nanpa, 2
#p mi mu, 2
#p mi len, 2
#p mije taso, 2
#p mije sama, 2
#p mije ona, 2
#p mije lawa, 2
#p mije la, 2
#p mi insa, 2
#p mi anpa, 2
#p meli ona, 2
#p meli olin, 2
#p meli la, 2
#p meli ante, 2
#p ma telo, 2
#p ma tawa, 2
#p ma suli, 2
#p ma seli, 2
#p ma ona, 2
#p ma o, 2
#p mani tan, 2
#p mani sina, 2
#p mani luka, 2
#p mani lili, 2
#p mani e, 2
#p ma moli, 2
#p mama kin, 2
#p ma lili, 2
#p ma kin, 2
#p ma kepeken, 2
#p ma awen, 2
#p lupa wan, 2
#p lupa suno, 2
#p lupa suli, 2
#p lukin pakala, 2
#p lukin anpa, 2
#p luka waso, 2
#p luka kepeken, 2
#p luka ike, 2
#p luka anu, 2
#p lon uta, 2
#p lon pona, 2
#p lon pimeja, 2
#p lon o, 2
#p lon nimi, 2
#p lon lukin, 2
#p lon lon, 2
#p lon kute, 2
#p lon kili, 2
#p lon kepeken, 2
#p lon kama, 2
#p lon kalama, 2
#p lon ijo, 2
#p lon en, 2
#p lon awen, 2
#p loje wan, 2
#p loje walo, 2
#p loje suwi, 2
#p loje pimeja, 2
#p loje e, 2
#p li uta, 2
#p lipu sona, 2
#p lipu seme, 2
#p lipu pona, 2
#p lipu ona, 2
#p lipu nanpa, 2
#p lipu laso, 2
#p lipu kule, 2
#p lipu ilo, 2
#p lipu e, 2
#p lipu anu, 2
#p lipu ala, 2
#p li poka, 2
#p li pi, 2
#p li ona, 2
#p linja walo, 2
#p linja tan, 2
#p linja suno, 2
#p linja sinpin, 2
#p linja nimi, 2
#p linja lili, 2
#p linja la, 2
#p linja e, 2
#p li mije, 2
#p lili sina, 2
#p lili sin, 2
#p lili sama, 2
#p lili o, 2
#p li linja, 2
#p lili kepeken, 2
#p lili ala, 2
#p li la, 2
#p li kasi, 2
#p li kala, 2
#p li ali, 2
#p lete pilin, 2
#p lete anu, 2
#p lete ante, 2
#p len walo, 2
#p len taso, 2
#p len suno, 2
#p len pimeja, 2
#p len lon, 2
#p len jelo, 2
#p len ante, 2
#p lawa taso, 2
#p lawa pona, 2
#p lawa ma, 2
#p la unpa, 2
#p la tu, 2
#p la tan, 2
#p laso sewi, 2
#p laso lon, 2
#p laso loje, 2
#p laso la, 2
#p laso kasi, 2
#p laso e, 2
#p la pu, 2
#p la pini, 2
#p lape tawa, 2
#p lape tan, 2
#p lape o, 2
#p lape kon, 2
#p lape anu, 2
#p la palisa, 2
#p la mute, 2
#p la meli, 2
#p la mani, 2
#p la lukin, 2
#p la jelo, 2
#p la en, 2
#p kulupu tu, 2
#p kulupu tomo, 2
#p kulupu pona, 2
#p kulupu nimi, 2
#p kulupu loje, 2
#p kule wawa, 2
#p kule tu, 2
#p kule sitelen, 2
#p kule selo, 2
#p kule ona, 2
#p kule kepeken, 2
#p ko wawa, 2
#p ko telo, 2
#p kon suli, 2
#p kon pimeja, 2
#p kon la, 2
#p kon ike, 2
#p kon en, 2
#p kon e, 2
#p ko monsi, 2
#p ko kule, 2
#p ko kili, 2
#p kiwen wawa, 2
#p kiwen sike, 2
#p kiwen seli, 2
#p kiwen pona, 2
#p kiwen pimeja, 2
#p kiwen palisa, 2
#p kiwen mi, 2
#p kiwen ma, 2
#p kiwen lili, 2
#p kiwen laso, 2
#p kiwen jelo, 2
#p kiwen ike, 2
#p kiwen ala, 2
#p kin lon, 2
#p kin anu, 2
#p kili tu, 2
#p kili sin, 2
#p kili sike, 2
#p kili seme, 2
#p kili nasa, 2
#p kili luka, 2
#p kili lon, 2
#p kili lipu, 2
#p kili la, 2
#p kili kepeken, 2
#p kepeken seli, 2
#p kepeken musi, 2
#p kepeken mi, 2
#p kepeken ma, 2
#p kepeken lupa, 2
#p kepeken lukin, 2
#p kepeken linja, 2
#p kepeken li, 2
#p kepeken ike, 2
#p kepeken anu, 2
#p ken wawa, 2
#p ken telo, 2
#p ken tan, 2
#p ken seme, 2
#p ken seli, 2
#p ken pini, 2
#p ken o, 2
#p ken ni, 2
#p ken mute, 2
#p ken musi, 2
#p ken meli, 2
#p ken mama, 2
#p ken ma, 2
#p ken kalama, 2
#p ken insa, 2
#p ken anu, 2
#p ken anpa, 2
#p ken ale, 2
#p kasi tomo, 2
#p kasi tan, 2
#p kasi seme, 2
#p kasi pan, 2
#p kasi nasa, 2
#p kasi lili, 2
#p kasi kiwen, 2
#p kasi kepeken, 2
#p kasi anu, 2
#p kasi ali, 2
#p kasi ale, 2
#p kama wile, 2
#p kama supa, 2
#p kama suno, 2
#p kama soweli, 2
#p kama ona, 2
#p kama ni, 2
#p kama mute, 2
#p kama moku, 2
#p kama lape, 2
#p kama kon, 2
#p kama kiwen, 2
#p kama kepeken, 2
#p kama anu, 2
#p kala wan, 2
#p kala tan, 2
#p kala pona, 2
#p kala pi, 2
#p kala mi, 2
#p kalama suwi, 2
#p kalama sama, 2
#p kalama lon, 2
#p kalama kepeken, 2
#p kalama ilo, 2
#p kala lon, 2
#p kala loje, 2
#p kala linja, 2
#p kala lili, 2
#p kala la, 2
#p kala ala, 2
#p jo sin, 2
#p jo ona, 2
#p jo awen, 2
#p jo a, 2
#p jelo pimeja, 2
#p jelo anu, 2
#p jan walo, 2
#p jan unpa, 2
#p jan pimeja, 2
#p jan pan, 2
#p jan pakala, 2
#p jan mije, 2
#p jan meli, 2
#p jan luka, 2
#p jan kon, 2
#p jan jaki, 2
#p jan esun, 2
#p jaki o, 2
#p jaki lon, 2
#p jaki a, 2
#p insa telo, 2
#p insa sijelo, 2
#p insa mute, 2
#p insa lupa, 2
#p insa lawa, 2
#p insa a, 2
#p ilo waso, 2
#p ilo utala, 2
#p ilo unpa, 2
#p ilo taso, 2
#p ilo sewi, 2
#p ilo palisa, 2
#p ilo ona, 2
#p ilo moli, 2
#p ilo ma, 2
#p ilo luka, 2
#p ilo lili, 2
#p ilo kon, 2
#p ilo kiwen, 2
#p ilo en, 2
#p ilo ante, 2
#p ilo ala, 2
#p ike pali, 2
#p ike kin, 2
#p ike en, 2
#p ijo tawa, 2
#p ijo sina, 2
#p ijo sama, 2
#p ijo pona, 2
#p ijo pimeja, 2
#p ijo ona, 2
#p ijo nanpa, 2
#p esun mute, 2
#p esun kepeken, 2
#p e poka, 2
#p en tu, 2
#p en suno, 2
#p en seli, 2
#p en open, 2
#p en oko, 2
#p en noka, 2
#p en mute, 2
#p en lawa, 2
#p en kon, 2
#p en kasi, 2
#p en kala, 2
#p en en, 2
#p e loje, 2
#p e kute, 2
#p e esun, 2
#p awen wawa, 2
#p awen sewi, 2
#p awen seli, 2
#p awen pali, 2
#p awen insa, 2
#p awen a, 2
#p a tomo, 2
#p a taso, 2
#p a tan, 2
#p a pona, 2
#p anu wawa, 2
#p anu tomo, 2
#p anu sina, 2
#p anu pona, 2
#p anu ona, 2
#p anu lon, 2
#p anu li, 2
#p anu jelo, 2
#p ante tenpo, 2
#p ante tawa, 2
#p ante taso, 2
#p ante o, 2
#p ante nimi, 2
#p ante lili, 2
#p ante kepeken, 2
#p ante ali, 2
#p anpa taso, 2
#p anpa supa, 2
#p anpa suno, 2
#p anpa ona, 2
#p anpa ma, 2
#p anpa lupa, 2
#p anpa lawa, 2
#p ale sin, 2
#p a len, 2
#p ale ma, 2
#p ala unpa, 2
#p ala suwi, 2
#p ala soweli, 2
#p alasa sin, 2
#p alasa pona, 2
#p alasa ona, 2
#p alasa la, 2
#p alasa kili, 2
#p alasa kama, 2
#p alasa jo, 2
#p alasa ala, 2
#p ala nasa, 2
#p ala mute, 2
#p ala lawa, 2
#p ala en, 2
#p ala anu, 2
#p ala ala, 2
#p a la, 2
#p akesi telo, 2
#p akesi sina, 2
#p akesi mute, 2
#p akesi meli, 2
#p akesi linja, 2
#p akesi kule, 2
#p akesi kin, 2
#p a akesi, 2
#p wile sin, 1
#p wile sewi, 1
#p wile seli, 1
#p wile pu, 1
#p wile poka, 1
#p wile open, 1
#p wile noka, 1
#p wile nimi, 1
#p wile nasin, 1
#p wile nasa, 1
#p wile nanpa, 1
#p wile mani, 1
#p wile luka, 1
#p wile len, 1
#p wile kulupu, 1
#p wile ilo, 1
#p wile anpa, 1
#p wile akesi, 1
#p weka wile, 1
#p weka sijelo, 1
#p weka sama, 1
#p weka pona, 1
#p weka pilin, 1
#p weka pali, 1
#p weka pakala, 1
#p weka nasin, 1
#p weka mute, 1
#p weka ko, 1
#p weka kin, 1
#p weka jan, 1
#p wawa weka, 1
#p wawa utala, 1
#p wawa taso, 1
#p wawa suwi, 1
#p wawa sin, 1
#p wawa sijelo, 1
#p wawa seli, 1
#p wawa nanpa, 1
#p wawa namako, 1
#p wawa musi, 1
#p wawa mun, 1
#p wawa mi, 1
#p wawa mani, 1
#p wawa lili, 1
#p wawa laso, 1
#p wawa kepeken, 1
#p wawa kasi, 1
#p wawa kalama, 1
#p wawa jan, 1
#p waso wan, 1
#p waso tu, 1
#p waso tawa, 1
#p waso taso, 1
#p waso sona, 1
#p waso sin, 1
#p waso musi, 1
#p waso moku, 1
#p waso mije, 1
#p waso meli, 1
#p waso lili, 1
#p waso laso, 1
#p waso e, 1
#p waso ante, 1
#p waso ale, 1
#p waso ala, 1
#p wan telo, 1
#p wan tan, 1
#p wan soweli, 1
#p wan sin, 1
#p wan sama, 1
#p wan kepeken, 1
#p wan kasi, 1
#p wan kalama, 1
#p walo tawa, 1
#p walo taso, 1
#p walo sewi, 1
#p walo pimeja, 1
#p walo o, 1
#p walo ni, 1
#p walo mute, 1
#p walo lipu, 1
#p walo linja, 1
#p walo lete, 1
#p walo jelo, 1
#p walo en, 1
#p walo anu, 1
#p walo ala, 1
#p uta wan, 1
#p uta suli, 1
#p uta soweli, 1
#p uta pona, 1
#p uta ni, 1
#p uta moku, 1
#p uta lon, 1
#p utala wawa, 1
#p utala uta, 1
#p utala toki, 1
#p utala sona, 1
#p utala sin, 1
#p utala sama, 1
#p utala pi, 1
#p utala pakala, 1
#p utala lawa, 1
#p utala kiwen, 1
#p utala kin, 1
#p utala kepeken, 1
#p utala ike, 1
#p utala en, 1
#p utala anu, 1
#p utala ante, 1
#p uta a, 1
#p unpa walo, 1
#p unpa ona, 1
#p unpa o, 1
#p unpa kepeken, 1
#p unpa kasi, 1
#p tu suli, 1
#p tu sina, 1
#p tu pini, 1
#p tu nasin, 1
#p tu mute, 1
#p tu lipu, 1
#p tu laso, 1
#p tu kin, 1
#p tu anu, 1
#p tu a, 1
#p tomo waso, 1
#p tomo wan, 1
#p tomo unpa, 1
#p tomo suno, 1
#p tomo sinpin, 1
#p tomo seme, 1
#p tomo selo, 1
#p tomo pini, 1
#p tomo pan, 1
#p tomo palisa, 1
#p tomo nena, 1
#p tomo mun, 1
#p tomo monsi, 1
#p tomo moli, 1
#p tomo mije, 1
#p tomo mani, 1
#p tomo ma, 1
#p tomo lete, 1
#p tomo kiwen, 1
#p tomo kin, 1
#p tomo jaki, 1
#p tomo ike, 1
#p tomo e, 1
#p tomo anu, 1
#p tomo ala, 1
#p toki wile, 1
#p toki utala, 1
#p toki tu, 1
#p toki sitelen, 1
#p toki sewi, 1
#p toki selo, 1
#p toki poka, 1
#p toki nanpa, 1
#p toki namako, 1
#p toki lipu, 1
#p toki lawa, 1
#p toki kulupu, 1
#p toki kule, 1
#p toki ken, 1
#p toki kalama, 1
#p toki kala, 1
#p toki esun, 1
#p toki en, 1
#p toki anu, 1
#p tenpo wile, 1
#p tenpo tan, 1
#p tenpo sona, 1
#p tenpo sijelo, 1
#p tenpo poka, 1
#p tenpo pipi, 1
#p tenpo ona, 1
#p tenpo nasa, 1
#p tenpo monsi, 1
#p tenpo moku, 1
#p tenpo lawa, 1
#p tenpo ijo, 1
#p tenpo e, 1
#p tenpo anu, 1
#p tenpo anpa, 1
#p telo weka, 1
#p telo uta, 1
#p telo tu, 1
#p telo sitelen, 1
#p telo sama, 1
#p telo pilin, 1
#p telo pan, 1
#p telo o, 1
#p telo nasin, 1
#p telo namako, 1
#p telo moli, 1
#p telo ma, 1
#p telo lukin, 1
#p telo ike, 1
#p telo awen, 1
#p telo anu, 1
#p telo anpa, 1
#p telo ali, 1
#p tawa utala, 1
#p tawa pipi, 1
#p tawa pini, 1
#p tawa pan, 1
#p tawa palisa, 1
#p tawa open, 1
#p tawa nasa, 1
#p tawa nanpa, 1
#p tawa moku, 1
#p tawa kule, 1
#p tawa kin, 1
#p tawa kili, 1
#p tawa kalama, 1
#p tawa ike, 1
#p tawa en, 1
#p tawa ali, 1
#p tawa alasa, 1
#p tawa a, 1
#p taso wawa, 1
#p taso taso, 1
#p taso sinpin, 1
#p taso sike, 1
#p taso sijelo, 1
#p taso sewi, 1
#p taso pona, 1
#p taso oko, 1
#p taso nanpa, 1
#p taso mute, 1
#p taso musi, 1
#p taso mun, 1
#p taso moli, 1
#p taso mije, 1
#p taso ma, 1
#p taso lupa, 1
#p taso kin, 1
#p taso kili, 1
#p taso kasi, 1
#p taso kalama, 1
#p taso ante, 1
#p taso ale, 1
#p taso alasa, 1
#p taso a, 1
#p tan wawa, 1
#p tan utala, 1
#p tan tawa, 1
#p tan taso, 1
#p tan sona, 1
#p tan sinpin, 1
#p tan pan, 1
#p tan palisa, 1
#p tan noka, 1
#p tan nasa, 1
#p tan nanpa, 1
#p tan mute, 1
#p tan mije, 1
#p tan linja, 1
#p tan la, 1
#p tan kulupu, 1
#p tan kule, 1
#p tan kili, 1
#p tan jaki, 1
#p tan ale, 1
#p tan alasa, 1
#p suwi toki, 1
#p suwi suli, 1
#p suwi sina, 1
#p suwi sin, 1
#p suwi sike, 1
#p suwi seme, 1
#p suwi pona, 1
#p suwi pimeja, 1
#p suwi pan, 1
#p suwi palisa, 1
#p suwi ona, 1
#p suwi kasi, 1
#p suwi insa, 1
#p suwi en, 1
#p suwi e, 1
#p suwi anu, 1
#p suwi ale, 1
#p supa tu, 1
#p supa tawa, 1
#p supa pona, 1
#p supa o, 1
#p supa noka, 1
#p supa nena, 1
#p supa mute, 1
#p supa musi, 1
#p supa lili, 1
#p supa len, 1
#p supa la, 1
#p supa awen, 1
#p supa anpa, 1
#p suno walo, 1
#p suno sewi, 1
#p suno sama, 1
#p suno ona, 1
#p suno luka, 1
#p suno loje, 1
#p suno kule, 1
#p suno kepeken, 1
#p suno insa, 1
#p suno esun, 1
#p suno ante, 1
#p suli wawa, 1
#p suli taso, 1
#p suli suli, 1
#p suli sin, 1
#p suli seme, 1
#p suli pilin, 1
#p suli loje, 1
#p suli linja, 1
#p suli laso, 1
#p suli kule, 1
#p suli kili, 1
#p suli en, 1
#p suli ante, 1
#p soweli wan, 1
#p soweli tu, 1
#p soweli toki, 1
#p soweli telo, 1
#p soweli taso, 1
#p soweli seme, 1
#p soweli seli, 1
#p soweli pipi, 1
#p soweli mu, 1
#p soweli moli, 1
#p soweli mama, 1
#p soweli loje, 1
#p soweli len, 1
#p soweli ko, 1
#p soweli kin, 1
#p soweli kalama, 1
#p soweli ali, 1
#p soweli a, 1
#p sona weka, 1
#p sona wan, 1
#p sona tenpo, 1
#p sona taso, 1
#p sona sitelen, 1
#p sona sewi, 1
#p sona pipi, 1
#p sona pana, 1
#p sona olin, 1
#p sona nasin, 1
#p sona namako, 1
#p sona luka, 1
#p sona ilo, 1
#p sona anu, 1
#p sona ante, 1
#p sona ali, 1
#p sona alasa, 1
#p sona akesi, 1
#p sitelen weka, 1
#p sitelen wawa, 1
#p sitelen walo, 1
#p sitelen tu, 1
#p sitelen taso, 1
#p sitelen tan, 1
#p sitelen soweli, 1
#p sitelen seme, 1
#p sitelen pimeja, 1
#p sitelen ona, 1
#p sitelen nimi, 1
#p sitelen nanpa, 1
#p sitelen mute, 1
#p sitelen lawa, 1
#p sitelen jelo, 1
#p sitelen anu, 1
#p sitelen ala, 1
#p sin taso, 1
#p sin suno, 1
#p sin sama, 1
#p sin pona, 1
#p sinpin utala, 1
#p sinpin uta, 1
#p sinpin telo, 1
#p sinpin taso, 1
#p sinpin sama, 1
#p sinpin poka, 1
#p sinpin pimeja, 1
#p sinpin ni, 1
#p sinpin musi, 1
#p sinpin lukin, 1
#p sinpin len, 1
#p sinpin lawa, 1
#p sinpin la, 1
#p sinpin kiwen, 1
#p sinpin kasi, 1
#p sinpin jelo, 1
#p sinpin jan, 1
#p sinpin ike, 1
#p sinpin anu, 1
#p sin lili, 1
#p sin kin, 1
#p sin kepeken, 1
#p sina unpa, 1
#p sina tu, 1
#p sina tomo, 1
#p sina telo, 1
#p sina suno, 1
#p sina suli, 1
#p sina soweli, 1
#p sina seli, 1
#p sina poka, 1
#p sin ante, 1
#p sina nasa, 1
#p sina nanpa, 1
#p sina mute, 1
#p sina linja, 1
#p sina lete, 1
#p sin ale, 1
#p sina anpa, 1
#p sina ali, 1
#p sina akesi, 1
#p sin a, 1
#p sike taso, 1
#p sike sina, 1
#p sike seme, 1
#p sike sama, 1
#p sike pimeja, 1
#p sike ona, 1
#p sike noka, 1
#p sike musi, 1
#p sike luka, 1
#p sike loje, 1
#p sike lili, 1
#p sike kon, 1
#p sike kepeken, 1
#p sike jelo, 1
#p sike jan, 1
#p sike ike, 1
#p sike a, 1
#p sijelo wan, 1
#p sijelo tu, 1
#p sijelo tan, 1
#p sijelo suli, 1
#p sijelo oko, 1
#p sijelo nasa, 1
#p sijelo mute, 1
#p sijelo moli, 1
#p sijelo mani, 1
#p sijelo lon, 1
#p sijelo lete, 1
#p sijelo jan, 1
#p sijelo ike, 1
#p sijelo ala, 1
#p sewi waso, 1
#p sewi sike, 1
#p sewi seme, 1
#p sewi pona, 1
#p sewi palisa, 1
#p sewi oko, 1
#p sewi nanpa, 1
#p sewi mute, 1
#p sewi loje, 1
#p sewi lipu, 1
#p sewi kin, 1
#p sewi kasi, 1
#p sewi kama, 1
#p sewi en, 1
#p sewi ali, 1
#p sewi ale, 1
#p sewi alasa, 1
#p seme sin, 1
#p seme pona, 1
#p seme poka, 1
#p seme ona, 1
#p seme nasin, 1
#p seme nasa, 1
#p selo waso, 1
#p selo tan, 1
#p selo sitelen, 1
#p selo sijelo, 1
#p selo pimeja, 1
#p selo noka, 1
#p selo mute, 1
#p selo lipu, 1
#p selo jan, 1
#p selo ale, 1
#p selo ala, 1
#p selo akesi, 1
#p seli wawa, 1
#p seli toki, 1
#p seli telo, 1
#p seli tan, 1
#p seli suwi, 1
#p seli sin, 1
#p seli sijelo, 1
#p seli pona, 1
#p seli pakala, 1
#p seli mi, 1
#p seli loje, 1
#p seli kepeken, 1
#p seli jelo, 1
#p seli insa, 1
#p seli ala, 1
#p seli a, 1
#p sama wan, 1
#p sama walo, 1
#p sama taso, 1
#p sama selo, 1
#p sama sama, 1
#p sama pali, 1
#p sama open, 1
#p sama meli, 1
#p sama loje, 1
#p sama lipu, 1
#p sama len, 1
#p sama kon, 1
#p sama kasi, 1
#p sama jaki, 1
#p sama ilo, 1
#p sama anu, 1
#p sama ante, 1
#p pu sina, 1
#p pu pona, 1
#p pu pi, 1
#p pu ni, 1
#p pu nanpa, 1
#p pu mi, 1
#p pu luka, 1
#p pu en, 1
#p pu e, 1
#p pu anu, 1
#p pu ante, 1
#p pona wawa, 1
#p pona wan, 1
#p pona walo, 1
#p pona tenpo, 1
#p pona suwi, 1
#p pona suno, 1
#p pona soweli, 1
#p pona sewi, 1
#p pona pona, 1
#p pona poka, 1
#p pona pana, 1
#p pona olin, 1
#p pona nimi, 1
#p pona nasin, 1
#p pona namako, 1
#p pona lawa, 1
#p pona kute, 1
#p pona esun, 1
#p pona awen, 1
#p pona ante, 1
#p poki tu, 1
#p poki supa, 1
#p poki sama, 1
#p poki poka, 1
#p poki nimi, 1
#p poki nanpa, 1
#p poki mute, 1
#p poki monsi, 1
#p poki lipu, 1
#p poki kasi, 1
#p poki jelo, 1
#p poki ilo, 1
#p poki ante, 1
#p poki ale, 1
#p poki akesi, 1
#p poka waso, 1
#p poka tenpo, 1
#p poka tawa, 1
#p poka pali, 1
#p poka ni, 1
#p poka mute, 1
#p poka mun, 1
#p poka ma, 1
#p poka lawa, 1
#p poka esun, 1
#p poka anu, 1
#p poka ala, 1
#p poka a, 1
#p pi walo, 1
#p pi taso, 1
#p pi suno, 1
#p pi seli, 1
#p pipi tan, 1
#p pipi seme, 1
#p pipi pona, 1
#p pipi pipi, 1
#p pipi pali, 1
#p pi pini, 1
#p pipi nasa, 1
#p pipi moli, 1
#p pipi jelo, 1
#p pipi ike, 1
#p pipi e, 1
#p pipi anu, 1
#p pipi akesi, 1
#p pi pakala, 1
#p pini toki, 1
#p pini soweli, 1
#p pini poka, 1
#p pini olin, 1
#p pini o, 1
#p pini nanpa, 1
#p pini ma, 1
#p pini lipu, 1
#p pini lape, 1
#p pini kin, 1
#p pini en, 1
#p pini awen, 1
#p pini ale, 1
#p pi ni, 1
#p pi mun, 1
#p pi moli, 1
#p pimeja wan, 1
#p pimeja tenpo, 1
#p pimeja tawa, 1
#p pimeja tan, 1
#p pimeja suwi, 1
#p pimeja open, 1
#p pimeja nasa, 1
#p pimeja lili, 1
#p pimeja laso, 1
#p pimeja kepeken, 1
#p pimeja kalama, 1
#p pimeja jelo, 1
#p pimeja e, 1
#p pilin unpa, 1
#p pilin tenpo, 1
#p pilin suli, 1
#p pilin sin, 1
#p pilin sijelo, 1
#p pilin sewi, 1
#p pilin pu, 1
#p pilin pipi, 1
#p pilin moli, 1
#p pilin moku, 1
#p pilin mije, 1
#p pilin meli, 1
#p pilin kon, 1
#p pilin ko, 1
#p pilin insa, 1
#p pilin en, 1
#p pilin ante, 1
#p pilin anpa, 1
#p pilin ale, 1
#p pilin akesi, 1
#p pi kepeken, 1
#p pi jo, 1
#p pi esun, 1
#p pi anpa, 1
#p pan tu, 1
#p pan taso, 1
#p pan suli, 1
#p pan sina, 1
#p pan sama, 1
#p pan pona, 1
#p pan linja, 1
#p pan lili, 1
#p pan kepeken, 1
#p pan kala, 1
#p pan jan, 1
#p pan insa, 1
#p pana telo, 1
#p pana taso, 1
#p pana sina, 1
#p pan anu, 1
#p pana nanpa, 1
#p pana mute, 1
#p pana lipu, 1
#p pana li, 1
#p pan ali, 1
#p pana ike, 1
#p pana esun, 1
#p pana anu, 1
#p pana anpa, 1
#p pali wan, 1
#p pali sijelo, 1
#p pali seme, 1
#p palisa wan, 1
#p palisa utala, 1
#p palisa telo, 1
#p palisa tawa, 1
#p palisa taso, 1
#p palisa tan, 1
#p palisa sina, 1
#p palisa palisa, 1
#p palisa monsi, 1
#p palisa mi, 1
#p palisa mani, 1
#p palisa loje, 1
#p palisa linja, 1
#p palisa jan, 1
#p palisa e, 1
#p palisa anu, 1
#p pali ma, 1
#p pali ken, 1
#p pali kama, 1
#p pakala weka, 1
#p pakala wawa, 1
#p pakala tenpo, 1
#p pakala taso, 1
#p pakala supa, 1
#p pakala sina, 1
#p pakala sijelo, 1
#p pakala selo, 1
#p pakala pilin, 1
#p pakala pi, 1
#p pakala ni, 1
#p pakala lawa, 1
#p pakala ko, 1
#p pakala jan, 1
#p pakala ilo, 1
#p pakala ale, 1
#p o wan, 1
#p o walo, 1
#p o taso, 1
#p o sin, 1
#p o pipi, 1
#p open wan, 1
#p open telo, 1
#p open sona, 1
#p open sina, 1
#p open sama, 1
#p open pilin, 1
#p open nimi, 1
#p open mute, 1
#p open lukin, 1
#p open lili, 1
#p open anu, 1
#p open ali, 1
#p open ale, 1
#p o ona, 1
#p ona wile, 1
#p ona soweli, 1
#p ona sina, 1
#p ona sin, 1
#p o nasin, 1
#p ona ona, 1
#p ona nimi, 1
#p ona nanpa, 1
#p o namako, 1
#p ona kiwen, 1
#p ona ali, 1
#p ona ala, 1
#p o mute, 1
#p o mani, 1
#p o lipu, 1
#p olin unpa, 1
#p olin toki, 1
#p olin sin, 1
#p olin pan, 1
#p olin pali, 1
#p olin o, 1
#p olin moli, 1
#p olin mije, 1
#p olin meli, 1
#p olin lawa, 1
#p o linja, 1
#p olin ante, 1
#p olin ali, 1
#p olin a, 1
#p oko wawa, 1
#p oko tu, 1
#p oko tan, 1
#p oko sama, 1
#p oko palisa, 1
#p oko mute, 1
#p oko laso, 1
#p oko anu, 1
#p oko ante, 1
#p o kin, 1
#p o kili, 1
#p o insa, 1
#p o anu, 1
#p o ali, 1
#p noka walo, 1
#p noka tu, 1
#p noka telo, 1
#p noka suli, 1
#p noka soweli, 1
#p noka seme, 1
#p noka monsi, 1
#p noka luka, 1
#p noka la, 1
#p noka kala, 1
#p noka ike, 1
#p ni tu, 1
#p ni toki, 1
#p ni suli, 1
#p ni sin, 1
#p ni pona, 1
#p ni pali, 1
#p ni ona, 1
#p ni nimi, 1
#p ni ni, 1
#p ni nanpa, 1
#p nimi tu, 1
#p nimi tawa, 1
#p nimi sike, 1
#p nimi sama, 1
#p nimi pipi, 1
#p nimi nena, 1
#p nimi nasin, 1
#p nimi nasa, 1
#p nimi musi, 1
#p nimi mama, 1
#p nimi lukin, 1
#p nimi lawa, 1
#p nimi kepeken, 1
#p nimi ala, 1
#p nimi akesi, 1
#p nimi a, 1
#p ni mama, 1
#p ni ali, 1
#p ni ale, 1
#p nena wan, 1
#p nena taso, 1
#p nena pimeja, 1
#p nena ona, 1
#p nena nasa, 1
#p nena lili, 1
#p nena la, 1
#p nena kon, 1
#p nena kiwen, 1
#p nasin wile, 1
#p nasin utala, 1
#p nasin tu, 1
#p nasin sin, 1
#p nasin sike, 1
#p nasin pimeja, 1
#p nasin pali, 1
#p nasin pakala, 1
#p nasin open, 1
#p nasin mute, 1
#p nasin moli, 1
#p nasin lupa, 1
#p nasin luka, 1
#p nasin len, 1
#p nasin ilo, 1
#p nasin esun, 1
#p nasin awen, 1
#p nasa suli, 1
#p nasa sina, 1
#p nasa sin, 1
#p nasa pilin, 1
#p nasa namako, 1
#p nasa laso, 1
#p nasa jaki, 1
#p nasa anu, 1
#p nasa ante, 1
#p nanpa sama, 1
#p nanpa ona, 1
#p nanpa nimi, 1
#p nanpa nasa, 1
#p nanpa monsi, 1
#p nanpa mi, 1
#p nanpa kepeken, 1
#p nanpa ali, 1
#p nanpa ala, 1
#p namako tu, 1
#p namako suli, 1
#p namako seme, 1
#p namako sama, 1
#p namako ona, 1
#p namako mi, 1
#p namako kepeken, 1
#p namako en, 1
#p namako ala, 1
#p mu utala, 1
#p mute wan, 1
#p mute suli, 1
#p mute sama, 1
#p mute pu, 1
#p mute poka, 1
#p mute palisa, 1
#p mu tenpo, 1
#p mute musi, 1
#p mute mun, 1
#p mute lukin, 1
#p mute kule, 1
#p mute kama, 1
#p mute kala, 1
#p mute ijo, 1
#p musi toki, 1
#p musi seli, 1
#p musi olin, 1
#p musi mi, 1
#p musi lukin, 1
#p musi lili, 1
#p musi lete, 1
#p musi kiwen, 1
#p musi kalama, 1
#p musi kala, 1
#p musi ilo, 1
#p musi anu, 1
#p musi ale, 1
#p mun wan, 1
#p mun walo, 1
#p mun suli, 1
#p mun sike, 1
#p mun pini, 1
#p mun pi, 1
#p mun ni, 1
#p mun nanpa, 1
#p mun moli, 1
#p mun lukin, 1
#p mun lete, 1
#p mun la, 1
#p mun kepeken, 1
#p mun e, 1
#p mu nasa, 1
#p mun anu, 1
#p mun ali, 1
#p mun ale, 1
#p mu la, 1
#p mu kin, 1
#p mu ike, 1
#p mu e, 1
#p mu anu, 1
#p mu anpa, 1
#p monsi uta, 1
#p monsi tawa, 1
#p monsi tan, 1
#p monsi suwi, 1
#p monsi supa, 1
#p monsi sitelen, 1
#p monsi seme, 1
#p monsi pilin, 1
#p monsi palisa, 1
#p monsi ma, 1
#p monsi linja, 1
#p monsi len, 1
#p monsi lawa, 1
#p monsi kasi, 1
#p monsi ike, 1
#p monsi en, 1
#p monsi ale, 1
#p moli tu, 1
#p moli taso, 1
#p moli sina, 1
#p moli sewi, 1
#p moli sama, 1
#p moli o, 1
#p moli ken, 1
#p moli kama, 1
#p moli kalama, 1
#p moli jan, 1
#p moli a, 1
#p moku wan, 1
#p moku sin, 1
#p moku sike, 1
#p moku sewi, 1
#p moku pini, 1
#p moku nasin, 1
#p moku namako, 1
#p moku linja, 1
#p moku kon, 1
#p moku kin, 1
#p moku ken, 1
#p moku a, 1
#p mi unpa, 1
#p mi tenpo, 1
#p mi seme, 1
#p mi poka, 1
#p mi pan, 1
#p mi oko, 1
#p mi noka, 1
#p mi meli, 1
#p mi mama, 1
#p mi lili, 1
#p mi kon, 1
#p mi kala, 1
#p mije unpa, 1
#p mije suwi, 1
#p mije soweli, 1
#p mije pona, 1
#p mije olin, 1
#p mije o, 1
#p mije mute, 1
#p mije kin, 1
#p mije e, 1
#p mije ante, 1
#p mije ala, 1
#p mije a, 1
#p mi jaki, 1
#p mi esun, 1
#p mi akesi, 1
#p meli wan, 1
#p meli unpa, 1
#p meli suwi, 1
#p meli sewi, 1
#p meli sama, 1
#p meli lili, 1
#p meli kin, 1
#p meli kala, 1
#p meli ala, 1
#p ma waso, 1
#p ma wan, 1
#p ma soweli, 1
#p ma sin, 1
#p ma sewi, 1
#p ma sama, 1
#p ma poka, 1
#p ma pakala, 1
#p ma open, 1
#p mani taso, 1
#p mani suli, 1
#p mani seme, 1
#p mani pali, 1
#p mani lon, 1
#p mani kepeken, 1
#p mani ilo, 1
#p mani en, 1
#p mani anu, 1
#p mani ali, 1
#p mani ale, 1
#p mani a, 1
#p ma nena, 1
#p ma mun, 1
#p mama wan, 1
#p mama open, 1
#p mama ma, 1
#p ma mama, 1
#p mama lon, 1
#p mama e, 1
#p mama a, 1
#p ma lupa, 1
#p ma loje, 1
#p ma kule, 1
#p ma kiwen, 1
#p ma anpa, 1
#p ma ali, 1
#p ma ala, 1
#p ma a, 1
#p lupa waso, 1
#p lupa tu, 1
#p lupa pini, 1
#p lupa pimeja, 1
#p lupa ona, 1
#p lupa nanpa, 1
#p lupa ma, 1
#p lupa la, 1
#p lupa kute, 1
#p lupa e, 1
#p lupa anpa, 1
#p lupa ale, 1
#p lukin wawa, 1
#p lukin wan, 1
#p lukin tu, 1
#p lukin sona, 1
#p lukin sewi, 1
#p lukin seme, 1
#p lukin poki, 1
#p lukin pimeja, 1
#p lukin o, 1
#p lukin nasa, 1
#p lukin monsi, 1
#p lukin lili, 1
#p lukin kin, 1
#p lukin kama, 1
#p lukin ike, 1
#p lukin ijo, 1
#p lukin ante, 1
#p luka taso, 1
#p luka tan, 1
#p luka palisa, 1
#p luka nanpa, 1
#p luka musi, 1
#p luka laso, 1
#p luka kin, 1
#p luka kasi, 1
#p luka jan, 1
#p luka en, 1
#p luka ale, 1
#p lon tu, 1
#p lon sama, 1
#p lon pu, 1
#p lon mute, 1
#p lon mun, 1
#p lon mu, 1
#p lon moli, 1
#p lon mije, 1
#p lon lili, 1
#p lon jaki, 1
#p lon ante, 1
#p lon ali, 1
#p lon alasa, 1
#p lon akesi, 1
#p loje tu, 1
#p loje sitelen, 1
#p loje sina, 1
#p loje sike, 1
#p loje ona, 1
#p loje nasa, 1
#p loje mute, 1
#p loje mi, 1
#p loje lili, 1
#p loje kin, 1
#p loje kili, 1
#p loje en, 1
#p loje ale, 1
#p loje a, 1
#p li taso, 1
#p li sijelo, 1
#p lipu wile, 1
#p lipu wan, 1
#p lipu walo, 1
#p lipu tomo, 1
#p lipu toki, 1
#p lipu taso, 1
#p lipu sewi, 1
#p lipu pali, 1
#p lipu musi, 1
#p lipu monsi, 1
#p lipu moli, 1
#p lipu mama, 1
#p lipu ma, 1
#p lipu lukin, 1
#p lipu lawa, 1
#p lipu kon, 1
#p lipu jelo, 1
#p lipu jan, 1
#p lipu en, 1
#p lipu ante, 1
#p lipu ale, 1
#p li o, 1
#p linja wawa, 1
#p linja sina, 1
#p linja sin, 1
#p linja sewi, 1
#p linja selo, 1
#p linja pona, 1
#p linja pana, 1
#p linja mi, 1
#p linja lukin, 1
#p linja lon, 1
#p linja len, 1
#p linja kin, 1
#p linja kili, 1
#p linja ale, 1
#p li lupa, 1
#p lili soweli, 1
#p lili sijelo, 1
#p lili pan, 1
#p lili nasin, 1
#p lili moli, 1
#p lili lukin, 1
#p lili len, 1
#p lili lawa, 1
#p lili kin, 1
#p lili kili, 1
#p lili ken, 1
#p lili ilo, 1
#p lili ike, 1
#p lili en, 1
#p lili anu, 1
#p lili ale, 1
#p li kin, 1
#p lete wawa, 1
#p lete tawa, 1
#p lete tan, 1
#p lete suli, 1
#p lete pimeja, 1
#p lete o, 1
#p lete ni, 1
#p lete nanpa, 1
#p lete mute, 1
#p lete moku, 1
#p lete mi, 1
#p lete lon, 1
#p lete lili, 1
#p lete kin, 1
#p lete ilo, 1
#p lete en, 1
#p lete ala, 1
#p lete a, 1
#p len wawa, 1
#p len tawa, 1
#p len supa, 1
#p len sijelo, 1
#p len seme, 1
#p len seli, 1
#p len sama, 1
#p len nena, 1
#p len mute, 1
#p len linja, 1
#p len kule, 1
#p len kon, 1
#p len awen, 1
#p len ale, 1
#p len ala, 1
#p lawa waso, 1
#p lawa tu, 1
#p lawa toki, 1
#p lawa tan, 1
#p lawa suli, 1
#p lawa o, 1
#p lawa nimi, 1
#p lawa ni, 1
#p la wan, 1
#p la walo, 1
#p lawa lete, 1
#p lawa kin, 1
#p lawa kepeken, 1
#p lawa jelo, 1
#p lawa ilo, 1
#p lawa anu, 1
#p lawa a, 1
#p la utala, 1
#p la uta, 1
#p la taso, 1
#p la suli, 1
#p laso walo, 1
#p laso telo, 1
#p laso suli, 1
#p laso sike, 1
#p laso sijelo, 1
#p laso pimeja, 1
#p laso ona, 1
#p laso mute, 1
#p laso ma, 1
#p laso kepeken, 1
#p laso jelo, 1
#p laso en, 1
#p laso a, 1
#p la sewi, 1
#p la seli, 1
#p la sama, 1
#p la poka, 1
#p la pi, 1
#p lape wawa, 1
#p lape tenpo, 1
#p lape sama, 1
#p lape nasa, 1
#p lape moli, 1
#p lape loje, 1
#p lape lape, 1
#p lape en, 1
#p lape a, 1
#p la oko, 1
#p la monsi, 1
#p la moli, 1
#p la lon, 1
#p la laso, 1
#p la lape, 1
#p la kute, 1
#p la kepeken, 1
#p la insa, 1
#p la anpa, 1
#p la ali, 1
#p la alasa, 1
#p kute wawa, 1
#p kute wan, 1
#p kute tawa, 1
#p kute taso, 1
#p kute mute, 1
#p kute lili, 1
#p kute insa, 1
#p kute en, 1
#p kute ale, 1
#p kulupu waso, 1
#p kulupu utala, 1
#p kulupu unpa, 1
#p kulupu taso, 1
#p kulupu tan, 1
#p kulupu soweli, 1
#p kulupu sama, 1
#p kulupu pali, 1
#p kulupu nasin, 1
#p kulupu meli, 1
#p kulupu luka, 1
#p kulupu lon, 1
#p kulupu laso, 1
#p kulupu ijo, 1
#p kulupu e, 1
#p kulupu ante, 1
#p kulupu ale, 1
#p kule wan, 1
#p kule sina, 1
#p kule seli, 1
#p kule sama, 1
#p kule pona, 1
#p kule pimeja, 1
#p kule namako, 1
#p kule musi, 1
#p kule moli, 1
#p kule ma, 1
#p kule laso, 1
#p kule la, 1
#p kule kulupu, 1
#p kule kama, 1
#p kule jelo, 1
#p kule anu, 1
#p ko pilin, 1
#p kon walo, 1
#p kon tu, 1
#p kon suwi, 1
#p kon sin, 1
#p kon seli, 1
#p kon pona, 1
#p kon poki, 1
#p kon o, 1
#p kon kasi, 1
#p kon jan, 1
#p kon ilo, 1
#p kon anu, 1
#p kon ante, 1
#p kon ala, 1
#p ko kon, 1
#p ko insa, 1
#p ko e, 1
#p ko a, 1
#p kiwen tu, 1
#p kiwen tomo, 1
#p kiwen tawa, 1
#p kiwen taso, 1
#p kiwen tan, 1
#p kiwen supa, 1
#p kiwen soweli, 1
#p kiwen sijelo, 1
#p kiwen mute, 1
#p kiwen mani, 1
#p kiwen lukin, 1
#p kiwen loje, 1
#p kiwen lipu, 1
#p kiwen la, 1
#p kiwen kepeken, 1
#p kiwen kasi, 1
#p kiwen insa, 1
#p kiwen awen, 1
#p kin tawa, 1
#p kin taso, 1
#p kin olin, 1
#p kin jan, 1
#p kili tan, 1
#p kili suli, 1
#p kili pan, 1
#p kili ma, 1
#p kili kin, 1
#p kili jelo, 1
#p kili jaki, 1
#p kili en, 1
#p kili anu, 1
#p kili ale, 1
#p kepeken wile, 1
#p kepeken weka, 1
#p kepeken waso, 1
#p kepeken tawa, 1
#p kepeken soweli, 1
#p kepeken sinpin, 1
#p kepeken sijelo, 1
#p kepeken seme, 1
#p kepeken selo, 1
#p kepeken pona, 1
#p kepeken poki, 1
#p kepeken pipi, 1
#p kepeken pilin, 1
#p kepeken pi, 1
#p kepeken pan, 1
#p kepeken pali, 1
#p kepeken olin, 1
#p kepeken oko, 1
#p kepeken mute, 1
#p kepeken moku, 1
#p kepeken mije, 1
#p kepeken loje, 1
#p kepeken lili, 1
#p kepeken lape, 1
#p kepeken kepeken, 1
#p kepeken ken, 1
#p kepeken jaki, 1
#p kepeken ijo, 1
#p ken wile, 1
#p ken utala, 1
#p ken unpa, 1
#p ken tu, 1
#p ken sina, 1
#p ken sin, 1
#p ken ona, 1
#p ken nasa, 1
#p ken mije, 1
#p ken mi, 1
#p ken len, 1
#p ken kule, 1
#p ken ken, 1
#p ken jaki, 1
#p ken esun, 1
#p ken en, 1
#p ken ali, 1
#p kasi wawa, 1
#p kasi wan, 1
#p kasi tu, 1
#p kasi sin, 1
#p kasi pona, 1
#p kasi o, 1
#p kasi namako, 1
#p kasi moli, 1
#p kasi luka, 1
#p kasi laso, 1
#p kasi ko, 1
#p kasi jelo, 1
#p kasi jaki, 1
#p kasi anpa, 1
#p kasi a, 1
#p kama waso, 1
#p kama tu, 1
#p kama tomo, 1
#p kama toki, 1
#p kama taso, 1
#p kama sitelen, 1
#p kama sina, 1
#p kama seli, 1
#p kama pan, 1
#p kama palisa, 1
#p kama o, 1
#p kama mije, 1
#p kama luka, 1
#p kama ko, 1
#p kama kala, 1
#p kama en, 1
#p kama awen, 1
#p kama ale, 1
#p kala wawa, 1
#p kala taso, 1
#p kalama waso, 1
#p kalama wan, 1
#p kalama tu, 1
#p kalama soweli, 1
#p kalama sewi, 1
#p kalama pona, 1
#p kalama mute, 1
#p kalama mu, 1
#p kalama lupa, 1
#p kalama luka, 1
#p kalama lape, 1
#p kalama la, 1
#p kalama kon, 1
#p kalama jan, 1
#p kalama awen, 1
#p kalama ante, 1
#p kalama ale, 1
#p kala luka, 1
#p kala ko, 1
#p kala kepeken, 1
#p kala kala, 1
#p kala jelo, 1
#p kala ike, 1
#p kala e, 1
#p jo sina, 1
#p jo pona, 1
#p jo pi, 1
#p jo o, 1
#p jo nanpa, 1
#p jo mute, 1
#p jo ma, 1
#p jo lon, 1
#p jo li, 1
#p jo la, 1
#p jo kin, 1
#p jo esun, 1
#p jo anu, 1
#p jo ale, 1
#p jelo walo, 1
#p jelo suno, 1
#p jelo pi, 1
#p jelo o, 1
#p jelo loje, 1
#p jelo la, 1
#p jelo ko, 1
#p jelo en, 1
#p jelo ale, 1
#p jan toki, 1
#p jan telo, 1
#p jan pini, 1
#p jan oko, 1
#p jan nimi, 1
#p jan namako, 1
#p jan moku, 1
#p jan mi, 1
#p jan lete, 1
#p jan laso, 1
#p jan kulupu, 1
#p jan kiwen, 1
#p jan kili, 1
#p jan kama, 1
#p jan jo, 1
#p jaki wawa, 1
#p jaki tomo, 1
#p jaki tawa, 1
#p jaki sina, 1
#p jaki pimeja, 1
#p jaki ona, 1
#p jaki noka, 1
#p jaki ni, 1
#p jaki len, 1
#p jaki kon, 1
#p jaki kin, 1
#p jaki anu, 1
#p jaki ale, 1
#p insa taso, 1
#p insa soweli, 1
#p insa sina, 1
#p insa sike, 1
#p insa moku, 1
#p insa mama, 1
#p insa ma, 1
#p insa lon, 1
#p insa la, 1
#p insa kili, 1
#p insa kasi, 1
#p insa ale, 1
#p ilo wawa, 1
#p ilo tu, 1
#p ilo seme, 1
#p ilo selo, 1
#p ilo sama, 1
#p ilo pona, 1
#p ilo pimeja, 1
#p ilo pali, 1
#p ilo open, 1
#p ilo oko, 1
#p ilo nasin, 1
#p ilo mute, 1
#p ilo mun, 1
#p ilo lon, 1
#p ilo loje, 1
#p ilo laso, 1
#p ilo lape, 1
#p ilo ken, 1
#p ilo ilo, 1
#p ilo ijo, 1
#p ilo e, 1
#p ilo ali, 1
#p ilo ale, 1
#p ilo a, 1
#p ike wawa, 1
#p ike tu, 1
#p ike telo, 1
#p ike suno, 1
#p ike sona, 1
#p ike seme, 1
#p ike seli, 1
#p ike sama, 1
#p ike pu, 1
#p ike moku, 1
#p ike kepeken, 1
#p ike ken, 1
#p ike kasi, 1
#p ike kama, 1
#p ike jan, 1
#p ike ike, 1
#p ike ante, 1
#p ike ali, 1
#p ijo suwi, 1
#p ijo sona, 1
#p ijo pakala, 1
#p ijo moku, 1
#p ijo lete, 1
#p ijo kiwen, 1
#p ijo ken, 1
#p ijo ilo, 1
#p ijo a, 1
#p e utala, 1
#p esun unpa, 1
#p esun tu, 1
#p esun tomo, 1
#p esun suli, 1
#p esun sitelen, 1
#p esun sin, 1
#p esun seme, 1
#p esun ona, 1
#p esun moku, 1
#p esun lipu, 1
#p esun kama, 1
#p esun ante, 1
#p esun ale, 1
#p e sewi, 1
#p e pana, 1
#p en wile, 1
#p en waso, 1
#p en utala, 1
#p en unpa, 1
#p en tomo, 1
#p en toki, 1
#p en supa, 1
#p en sitelen, 1
#p en sinpin, 1
#p en sike, 1
#p en sijelo, 1
#p en sewi, 1
#p en selo, 1
#p en pona, 1
#p en pan, 1
#p en palisa, 1
#p en olin, 1
#p en nena, 1
#p en namako, 1
#p en musi, 1
#p en moli, 1
#p en mama, 1
#p en lon, 1
#p en loje, 1
#p en linja, 1
#p en len, 1
#p en lape, 1
#p en kute, 1
#p en kulupu, 1
#p en kepeken, 1
#p e li, 1
#p e laso, 1
#p e jelo, 1
#p e insa, 1
#p e anu, 1
#p e alasa, 1
#p e a, 1
#p a wile, 1
#p awen walo, 1
#p awen tenpo, 1
#p awen telo, 1
#p awen suli, 1
#p awen sin, 1
#p awen ona, 1
#p awen ni, 1
#p awen nena, 1
#p awen nasa, 1
#p awen nanpa, 1
#p awen mute, 1
#p awen musi, 1
#p awen monsi, 1
#p awen moli, 1
#p awen mani, 1
#p awen lawa, 1
#p awen kili, 1
#p awen jan, 1
#p awen ilo, 1
#p awen awen, 1
#p awen anpa, 1
#p awen ale, 1
#p a toki, 1
#p a telo, 1
#p a soweli, 1
#p a seme, 1
#p a pi, 1
#p anu weka, 1
#p anu wan, 1
#p anu tu, 1
#p anu toki, 1
#p anu taso, 1
#p anu tan, 1
#p anu soweli, 1
#p anu sinpin, 1
#p anu sike, 1
#p anu pimeja, 1
#p anu pi, 1
#p anu o, 1
#p anu mute, 1
#p anu musi, 1
#p anu meli, 1
#p anu lupa, 1
#p anu luka, 1
#p anu lipu, 1
#p anu linja, 1
#p anu laso, 1
#p anu la, 1
#p anu kasi, 1
#p anu jo, 1
#p anu ijo, 1
#p anu anu, 1
#p ante wawa, 1
#p ante sike, 1
#p ante sama, 1
#p ante nasa, 1
#p ante mi, 1
#p ante luka, 1
#p ante kama, 1
#p ante anu, 1
#p ante ale, 1
#p anpa tenpo, 1
#p anpa noka, 1
#p anpa ni, 1
#p anpa lipu, 1
#p anpa lili, 1
#p anpa kiwen, 1
#p anpa jan, 1
#p anpa en, 1
#p anpa a, 1
#p a nimi, 1
#p a moku, 1
#p a lukin, 1
#p ali tawa, 1
#p ali tan, 1
#p ali pi, 1
#p ali mute, 1
#p ali ali, 1
#p ale wile, 1
#p ale waso, 1
#p ale taso, 1
#p ale sijelo, 1
#p ale pona, 1
#p ale luka, 1
#p ale ike, 1
#p ale en, 1
#p ale awen, 1
#p ala wawa, 1
#p ala wan, 1
#p ala walo, 1
#p ala utala, 1
#p ala uta, 1
#p ala tomo, 1
#p ala sewi, 1
#p ala seli, 1
#p alasa wawa, 1
#p alasa utala, 1
#p alasa toki, 1
#p alasa tan, 1
#p alasa suli, 1
#p alasa soweli, 1
#p alasa pana, 1
#p alasa pan, 1
#p alasa pali, 1
#p alasa ni, 1
#p alasa moli, 1
#p alasa lukin, 1
#p alasa lon, 1
#p alasa len, 1
#p alasa lape, 1
#p ala pu, 1
#p ala poki, 1
#p ala mu, 1
#p ala mani, 1
#p ala lipu, 1
#p ala lili, 1
#p ala kule, 1
#p ala kon, 1
#p ala kasi, 1
#p ala kalama, 1
#p ala jan, 1
#p ala jaki, 1
#p ala esun, 1
#p ala alasa, 1
#p ala akesi, 1
#p akesi wawa, 1
#p akesi tu, 1
#p akesi tawa, 1
#p akesi taso, 1
#p akesi suwi, 1
#p akesi pona, 1
#p akesi o, 1
#p akesi mije, 1
#p akesi kepeken, 1
#p akesi jan, 1
#p akesi ante, 1
#p akesi ala, 1
#p akesi akesi, 1
#p a kalama, 1
#p a ijo, 1
#p a ale, 1
